DROP FOREIGN TABLE IF EXISTS mp_film CASCADE;

CREATE FOREIGN TABLE mp_film (
	film_ipoc varchar(30) NULL,
	film_poc varchar(9) OPTIONS(key 'true') NOT NULL,
	film_poc_title varchar(40) NULL,
	film_licen_dfrom timestamp(0) NULL,
	film_licen_dto timestamp(0) NULL,
	film_licen_run int2 NULL,
	lang_code varchar(2) NULL,
	film_production varchar(4) NULL,
	film_action_need bpchar(1) NULL,
	film_color varchar(1) NULL,
	catgenre_code varchar(4) NULL,
	catsri_code varchar(3) NULL,
	catslot_code varchar(3) NULL,
	film_epi_total int2 NULL,
	film_epi_start int2 NULL,
	film_amount_trx numeric(15, 2) NULL,
	film_amount_home numeric(15, 2) NULL,
	film_sharing varchar(1) NULL,
	film_drama varchar(1) NULL,
	update_user varchar(10) NOT NULL,
	update_date timestamp(0) NOT NULL,
	row_id varchar(18) OPTIONS(key 'true') NOT NULL,
	curr_code varchar(5) NULL,
	distri_code varchar(6) NULL,
	run1 numeric NULL,
	run2 numeric NULL,
	run3 numeric NULL,
	run4 numeric NULL,
	run5 numeric NULL,
	p_sharing numeric(5, 2) NULL,
	"cast" varchar(254) NULL,
	director varchar(254) NULL,
	synopsys varchar(4000) NULL,
	remarks varchar(254) NULL,
	rev_share bpchar(1) NULL,
	r_sharing numeric(5, 2) NULL,
	at_share bpchar(1) NULL,
	a_share numeric(5, 2) NULL,
	epi_to numeric NULL,
	b_time bpchar(1) NULL,
	bonus_code varchar(10) NULL,
	running_time numeric NULL,
	free_rights bpchar(1) NULL,
	copy_source varchar(10) NULL,
	production_date timestamp(0) NULL,
	copy_reason varchar(10) NULL,
	revision_no numeric NULL,
	row_id_film varchar(18) NULL,
	slot_rate varchar(5) NULL,
	length_per_episode numeric NULL,
	year_release numeric NULL,
	program_type varchar(4) NULL,
	sub_type varchar(2) NULL,
	original_cost numeric NULL,
	shared_cost numeric NULL,
	sctv_cost numeric NULL,
	grn varchar(10) NULL,
	mat_loan_flag bpchar(1) NULL,
	iden_flag bpchar(1) NULL,
	material_type bpchar(1) NULL,
	color bpchar(1) NULL,
	txn_id varchar(30) NULL,
	txn_date timestamp(0) NULL,
	package_name varchar(200) NULL,
	producers varchar(254) NULL,
	stars_film varchar(254) NULL,
	co_stars varchar(254) NULL,
	grading varchar(100) NULL,
	made_for bpchar(1) NULL,
	target_aud varchar(100) NULL,
	use_restrictions varchar(254) NULL,
	live_program bpchar(1) NULL,
	banner_epi_max_no numeric NULL,
	cat_code varchar(10) NULL,
	cat_group_code varchar(10) NULL,
	tvr numeric(10, 2) NULL,
	cprp numeric(10, 2) NULL,
	bonus_flag varchar(1) NULL,
	barter_flag varchar(1) NULL,
	live_event varchar(1) NULL,
	allow_ros varchar(1) NULL,
	cb_pattern_code varchar(10) NULL,
	prodformat varchar(5) NULL,
	row_id_old varchar(18) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'MP_FILM');