DROP FOREIGN TABLE IF EXISTS mt_prod1;

CREATE FOREIGN TABLE mt_prod1 (
	prod_code varchar(20) OPTIONS(key 'true') NOT NULL,
	prod_version varchar(5) OPTIONS(key 'true') NOT NULL,
	prod_version_name varchar(50) NULL,
	prod_duration varchar(8) NULL,
	prod_som varchar(8) NULL,
	prod_eom varchar(8) NULL,
	schobj_code varchar(5) NULL,
	house_no varchar(100) NULL,
	machine_code varchar(5) NULL,
	prod_vclip bpchar(1) NULL,
	prod_expired timestamp(0) NULL,
	prod_censor varchar(30) NULL,
	prod_censord timestamp(0) NULL,
	prod_censore timestamp(0) NULL,
	material_code varchar(3) NULL,
	prod_remark varchar(1000) NULL,
	non_active timestamp(0) NULL,
	update_user varchar(10) NOT NULL,
	update_date timestamp(0) NOT NULL,
	row_id varchar(18) NOT NULL,
	prod_duration_s int4 NULL,
	prod_duration_f int2 NULL,
	old_rec bpchar(1) NULL,
	filepath varchar(4000) NULL,
	client_code varchar(20) NULL,
	sales_code varchar(5) NULL,
	returned bpchar(1) NULL,
	cut_no varchar(10) NULL,
	master_copy_no varchar(50) NULL,
	start_date timestamp(0) NULL,
	seg_in_tape varchar(4) NULL,
	in_server varchar(1) NULL,
	row_id_mversion varchar(18) NULL,
	is_mversion bpchar(1) NULL,
	video_path varchar(4000) NULL,
	dateingest timestamp(0) NULL,
	datereturned timestamp(0) NULL,
	dateserverdelete timestamp(0) NULL,
	pathname varchar(4000) NULL,
	housenolink varchar(100) NULL,
	agen_code varchar(20) NULL,
	revision_no numeric NULL,
	revision_remarks varchar(500) NULL,
	run_code varchar(6) NULL,
	schobj_time bpchar(1) NULL,
	tapedur varchar(8) NULL,
	old_prod_version varchar(5) NULL,
	copy_prod_code varchar(20) NULL,
	copy_prod_version varchar(5) NULL,
	entry_date timestamp(0) NULL,
	entry_user varchar(20) NULL,
	material_dur varchar(8) NULL,
	new_row bpchar(1) NULL,
	flag_receive bpchar(1) NULL,
	date_receive timestamp(0) NULL,
	qc_status bpchar(1) NULL,
	flag_suspend bpchar(1) NULL,
	date_suspend_from timestamp(0) NULL,
	date_suspend_to timestamp(0) NULL,
	hd_sd_flag varchar(2) NULL,
	frame_rate numeric NULL,
	lang_code varchar(2) NULL,
	qc_user varchar(200) NULL,
	qc_date timestamp(0) NULL,
	qc_trans_status bpchar(1) NULL,
	qc_trans_user varchar(200) NULL,
	qc_trans_date timestamp(0) NULL,
	qc_tech_status bpchar(1) NULL,
	qc_tech_user varchar(200) NULL,
	qc_tech_date timestamp(0) NULL,
	snp_required bpchar(1) NULL,
	prod_version_alt_name varchar(100) NULL,
	qc_from varchar(1) NULL,
	qc_trans_from varchar(1) NULL,
	qc_tech_from varchar(1) NULL,
	file_ext varchar(10) NULL,
	audio_ext varchar(10) NULL,
	receiveform_sign bpchar(1) NULL,
	salesmanager_sign bpchar(1) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'MT_PROD1');