DROP FOREIGN TABLE IF EXISTS pur_episode_hdr;

CREATE FOREIGN TABLE pur_episode_hdr (
	pur_contract_no varchar(20) OPTIONS(key 'true') NOT NULL,
	revision_no numeric OPTIONS(key 'true') NOT NULL,
	row_id_film varchar(18) OPTIONS(key 'true') NOT NULL,
	film_epi varchar(8) OPTIONS(key 'true') NOT NULL,
	film_epi_title varchar(100) NULL,
	epi_value numeric(15, 2) NULL,
	epi_format varchar(30) NULL,
	material_qty numeric NULL,
	uom varchar(10) NULL,
	delivery_sch_date timestamp(0) NULL,
	actual_rcvd_date timestamp(0) NULL,
	"comments" varchar(1000) NULL,
	mat_loan_flag bpchar(1) NULL,
	update_user varchar(30) NULL,
	update_date timestamp(0) NULL,
	row_id varchar(18) NULL,
	rcvd_status varchar(1) NULL,
	org_lang_code varchar(2) NULL,
	review_status varchar(10) NULL,
	reviewer_name varchar(30) NULL,
	results varchar(250) NULL,
	material_type varchar(3) NULL,
	epi_home_val numeric(15, 2) NULL,
	alternate_title varchar(50) NULL,
	org_name varchar(200) NULL,
	dub bpchar(1) NULL,
	sub bpchar(1) NULL,
	dub_lang varchar(2) NULL,
	sub_lang varchar(2) NULL,
	mat_in_stock bpchar(1) NULL,
	promo bpchar(1) NULL,
	music_cue_sheet bpchar(1) NULL,
	trailer bpchar(1) NULL,
	insertmode varchar(1) NULL,
	stls_no varchar(50) NULL,
	length_epi numeric NULL,
	scripts varchar(1) NULL,
	target_aud varchar(10) NULL,
	brochures varchar(1) NULL,
	script_arr_date timestamp(0) NULL,
	script_ret_date timestamp(0) NULL,
	brochure_arr_date timestamp(0) NULL,
	brochure_ret_date timestamp(0) NULL,
	censorboardcat varchar(50) NULL,
	censorendlicinfo varchar(50) NULL,
	print_location varchar(50) NULL,
	synopsis varchar(4000) NULL,
	pattern_code varchar(10) NULL,
	live_program bpchar(1) NULL,
	banner_epi_no numeric NULL,
	film_poc varchar(9) NULL,
	row_id_poc varchar(18) NULL,
	bannername varchar(40) NULL,
	lic_start_date timestamp(0) NULL,
	lic_end_date timestamp(0) NULL,
	package_name varchar(200) NULL,
	org_row_id varchar(18) NULL,
	exp_runs numeric NULL,
	year_release numeric NULL,
	program_type bpchar(4) NULL,
	sub_type varchar(2) NULL,
	color_bw bpchar(1) NULL,
	stars_film varchar(254) NULL,
	directors varchar(254) NULL,
	producers varchar(254) NULL,
	grading varchar(10) NULL,
	made_for bpchar(1) NULL,
	co_stars varchar(254) NULL,
	play_used numeric NULL,
	production varchar(10) NULL,
	tls_num varchar(50) NULL,
	last_date timestamp(0) NULL,
	last_time varchar(20) NULL,
	material_id varchar(25) NULL,
	st_time varchar(20) NULL,
	ed_time varchar(20) NULL,
	temp_title varchar(50) NULL,
	exchange_code numeric NULL,
	production_house varchar(100) NULL,
	music_label varchar(100) NULL,
	row_id_dummy varchar(18) NULL,
	hold_lic_start timestamp(0) NULL,
	hold_lic_end timestamp(0) NULL,
	holiday_code varchar(10) NULL,
	prize_code varchar(10) NULL,
	quality_code varchar(10) NULL,
	avail_start_date timestamp(0) NULL,
	avail_end_date timestamp(0) NULL,
	usage_code varchar(10) NULL,
	remark varchar(100) NULL,
	sch_comments varchar(254) NULL,
	user_field1 varchar(254) NULL,
	user_field2 varchar(254) NULL,
	user_field3 varchar(254) NULL,
	budget_code varchar(100) NULL,
	temp_programid varchar(20) NULL,
	temp_licstartdt varchar(20) NULL,
	temp_licenddt varchar(20) NULL,
	pur_seqno numeric NULL,
	exchange_rate numeric(15, 2) NULL,
	currency_code varchar(10) NULL,
	synopsis_bkup varchar(4000) NULL,
	row_id_epi varchar(18) NULL,
	translator_name varchar(50) NULL,
	translator_date timestamp(0) NULL,
	staff_name varchar(50) NULL,
	staff_date timestamp(0) NULL,
	backup_no int8 NULL,
	backup_date timestamp(0) NULL,
	remark_subtitle varchar(250) NULL,
	remark_dubbing varchar(250) NULL,
	dubbing_date timestamp(0) NULL,
	row_id_amor varchar(18) NULL,
	fm_comment varchar(254) NULL,
	epi_add_date timestamp(0) NULL,
	status_eval varchar(2) NULL,
	date_eval timestamp(0) NULL,
	ready_in_trans varchar(1) NULL,
	mat_exp_arr_date timestamp(0) NULL,
	dub_required varchar(1) NULL,
	subt_required varchar(1) NULL,
	personality varchar(500) NULL,
	music_director varchar(254) NULL,
	ppn numeric(5, 2) NULL,
	pph numeric(5, 2) NULL,
	ppn_val numeric(15, 2) NULL,
	pph_val numeric(15, 2) NULL,
	exch_arr numeric(15, 2) NULL,
	epi_value_tax numeric(15, 2) NULL,
	add_cost numeric(15, 2) NULL,
	epi_no numeric NULL,
	epi_no_suff varchar(5) NULL,
	film_epi_parent varchar(4) NULL,
	split_flag bpchar(1) NULL,
	promo_pict bytea NULL,
	file_name varchar(100) NULL,
	file_type varchar(10) NULL,
	old_path varchar(100) NULL,
	deal_type varchar(6) NULL,
	program_category varchar(3) NULL,
	prog_id_old varchar(30) NULL,
	epi_title_old varchar(100) NULL,
	lic_end_date_temp varchar(8) NULL,
	epi_value_temp varchar(100) NULL,
	epi_home_value_temp varchar(100) NULL,
	temp_prog_id_old varchar(20) NULL,
	lic_start_date_temp varchar(20) NULL,
	program_id varchar(20) NULL,
	seq_num numeric(15, 2) NULL,
	"owner" varchar(3) NULL,
	prog_group varchar(2) NULL,
	exp_runs_po numeric NULL,
	epi_po_flag bpchar(1) NULL,
	sap_material_id varchar(14) NULL,
	sap_amt numeric NULL,
	run_repeat varchar(1) NULL,
	is_row_id varchar(18) NULL,
	run_org numeric NULL,
	day_repeat numeric NULL,
	hours_repeat numeric NULL,
	schn_repeat bpchar(1) NULL,
	max_repeat numeric NULL,
	run_license_flag varchar(1) NULL,
	subtitling varchar(1) NULL,
	snp bpchar(1) NULL,
	alt_title varchar(100) NULL,
	season varchar(100) NULL,
	amor_type varchar(1) NULL,
	sales_flag bpchar(1) NULL,
	row_id_sales varchar(18) NULL,
	contract_ref_num varchar(30) NULL,
	flag_m varchar(1) NULL,
	row_id_old varchar(18) NULL,
	epk_avail_flag bpchar(1) NULL,
	url varchar(300) NULL,
	sku varchar(50) NULL,
	product_name varchar(200) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'PUR_EPISODE_HDR');