DROP FOREIGN TABLE IF EXISTS purchase_contract_dtl;

CREATE FOREIGN TABLE purchase_contract_dtl (
	pur_contract_no varchar(30) OPTIONS(key 'true') NOT NULL,
	revision_no numeric OPTIONS(key 'true') NOT NULL,
	film_title varchar(100) NULL,
	lic_start_date timestamp(0) NULL,
	lic_end_date timestamp(0) NULL,
	num_of_episodes numeric NULL,
	length_per_epi numeric NULL,
	year_release numeric NULL,
	program_type bpchar(4) NULL,
	sub_type varchar(2) NULL,
	program_length numeric NULL,
	"cast" varchar(50) NULL,
	material_rcvd_status bpchar(1) NULL,
	short_desc varchar(100) NULL,
	original_cost numeric(15, 2) NULL,
	shared_cost numeric(15, 2) NULL,
	sctv_cost numeric(15, 2) NULL,
	update_user varchar(30) NOT NULL,
	update_date timestamp(0) NULL,
	row_id varchar(18) OPTIONS(key 'true') NOT NULL,
	org_lang_code varchar(2) NULL,
	home_cost numeric(15, 2) NULL,
	exp_runs numeric NULL,
	note varchar(100) NULL,
	color_bw bpchar(1) NULL,
	stars_film varchar(254) NULL,
	co_stars varchar(254) NULL,
	directors varchar(254) NULL,
	producers varchar(254) NULL,
	"comments" varchar(254) NULL,
	grading varchar(100) NULL,
	use_restrictions varchar(100) NULL,
	target_aud varchar(100) NULL,
	made_for bpchar(1) NULL,
	actual_air_date timestamp(0) NULL,
	synopsis varchar(4000) NULL,
	insertmode varchar(1) NULL,
	seqno numeric NULL,
	pattern_code varchar(10) NULL,
	bonus_code varchar(10) NULL,
	live_program bpchar(1) NULL,
	copycost bpchar(1) NULL,
	bannername varchar(40) NULL,
	film_poc varchar(9) NULL,
	row_id_poc varchar(18) NULL,
	exchange_code numeric NULL,
	catsri_code varchar(3) NULL,
	catslot_code varchar(3) NULL,
	film_drama varchar(1) NULL,
	curr_code varchar(5) NULL,
	dist_code varchar(6) NULL,
	hold_lic_start timestamp(0) NULL,
	hold_lic_end timestamp(0) NULL,
	avail_start_date timestamp(0) NULL,
	avail_end_date timestamp(0) NULL,
	temp_programid varchar(10) NULL,
	pur_seqno numeric NULL,
	is_series bpchar(1) NULL,
	nett_gross_flag bpchar(1) NULL,
	program_category varchar(3) NULL,
	pcountry_code varchar(3) NULL,
	life_long_rights varchar(1) NULL,
	unlimited_runs varchar(1) NULL,
	deal_type varchar(6) NULL,
	banner_ref varchar(60) NULL,
	web_link varchar(200) NULL,
	suffix varchar(5) NULL,
	start_no numeric NULL,
	end_no numeric NULL,
	prog_id numeric NULL,
	film_title_old varchar(100) NULL,
	lic_end_date_temp varchar(10) NULL,
	lic_start_date_old varchar(10) NULL,
	prog_group varchar(2) NULL,
	num_of_episodes_po numeric NULL,
	exp_runs_po numeric NULL,
	sap_cost numeric(15, 2) NULL,
	budget_code varchar(100) NULL,
	sap_amor numeric(15, 2) NULL,
	run_repeat varchar(1) NULL,
	is_row_id varchar(18) NULL,
	subtitling varchar(1) NULL,
	channel_afi varchar(3) NULL,
	source_copy varchar(1) NULL,
	run_license_flag varchar(1) NULL,
	snp bpchar(1) NULL,
	schn_repeat bpchar(1) NULL,
	hours_repeat numeric NULL,
	day_repeat numeric NULL,
	max_repeat numeric NULL,
	amor_type varchar(1) NULL,
	contract_ref_num varchar(30) NULL,
	sts_program bpchar(1) NULL,
	row_id_old varchar(18) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'PURCHASE_CONTRACT_DTL');