DROP MATERIALIZED VIEW IF EXISTS purchase_contract_dtl;

CREATE materialized VIEW purchase_contract_dtl as
	SELECT 
		pur_contract_no,
		revision_no,
		film_title,
		lic_start_date,
		lic_end_date,
		num_of_episodes,
		length_per_epi,
		year_release,
		program_type,
		sub_type,
		program_length,
		"cast",
		material_rcvd_status,
		short_desc,
		original_cost,
		shared_cost,
		sctv_cost,
		update_user,
		update_date,
		row_id,
		org_lang_code,
		home_cost,
		exp_runs,
		note,
		color_bw,
		stars_film,
		co_stars,
		directors,
		producers,
		"comments",
		grading,
		use_restrictions,
		target_aud,
		made_for,
		actual_air_date,
		synopsis,
		insertmode,
		seqno,
		pattern_code,
		bonus_code,
		live_program,
		copycost,
		bannername,
		film_poc,
		row_id_poc,
		exchange_code,
		catsri_code,
		catslot_code,
		film_drama,
		curr_code,
		dist_code,
		hold_lic_start,
		hold_lic_end,
		avail_start_date,
		avail_end_date,
		temp_programid,
		pur_seqno,
		is_series,
		nett_gross_flag,
		program_category,
		pcountry_code,
		life_long_rights,
		unlimited_runs,
		deal_type,
		banner_ref,
		web_link,
		suffix,
		start_no,
		end_no,
		prog_id,
		film_title_old,
		lic_end_date_temp,
		lic_start_date_old,
		prog_group,
		num_of_episodes_po,
		exp_runs_po,
		sap_cost,
		budget_code,
		sap_amor,
		run_repeat,
		is_row_id,
		subtitling,
		channel_afi,
		source_copy,
		run_license_flag,
		snp,
		schn_repeat,
		hours_repeat,
		day_repeat,
		max_repeat,
		amor_type,
		contract_ref_num,
		sts_program,
		row_id_old
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					pur_contract_no,
					revision_no,
					film_title,
					lic_start_date,
					lic_end_date,
					num_of_episodes,
					length_per_epi,
					year_release,
					program_type,
					sub_type,
					program_length,
					"cast",
					material_rcvd_status,
					short_desc,
					original_cost,
					shared_cost,
					sctv_cost,
					update_user,
					update_date,
					row_id,
					org_lang_code,
					home_cost,
					exp_runs,
					note,
					color_bw,
					stars_film,
					co_stars,
					directors,
					producers,
					"comments",
					grading,
					use_restrictions,
					target_aud,
					made_for,
					actual_air_date,
					synopsis,
					insertmode,
					seqno,
					pattern_code,
					bonus_code,
					live_program,
					copycost,
					bannername,
					film_poc,
					row_id_poc,
					exchange_code,
					catsri_code,
					catslot_code,
					film_drama,
					curr_code,
					dist_code,
					hold_lic_start,
					hold_lic_end,
					avail_start_date,
					avail_end_date,
					temp_programid,
					pur_seqno,
					is_series,
					nett_gross_flag,
					program_category,
					pcountry_code,
					life_long_rights,
					unlimited_runs,
					deal_type,
					banner_ref,
					web_link,
					suffix,
					start_no,
					end_no,
					prog_id,
					film_title_old,
					lic_end_date_temp,
					lic_start_date_old,
					prog_group,
					num_of_episodes_po,
					exp_runs_po,
					sap_cost,
					budget_code,
					sap_amor,
					run_repeat,
					is_row_id,
					subtitling,
					channel_afi,
					source_copy,
					run_license_flag,
					snp,
					schn_repeat,
					hours_repeat,
					day_repeat,
					max_repeat,
					amor_type,
					contract_ref_num,
					sts_program,
					row_id_old
				FROM gen21.purchase_contract_dtl
			'
   		) tbl(
			pur_contract_no varchar(30),
			revision_no numeric,
			film_title varchar(100),
			lic_start_date timestamp(0),
			lic_end_date timestamp(0),
			num_of_episodes numeric,
			length_per_epi numeric,
			year_release numeric,
			program_type bpchar(4),
			sub_type varchar(2),
			program_length numeric,
			"cast" varchar(50),
			material_rcvd_status bpchar(1),
			short_desc varchar(100),
			original_cost numeric(15, 2),
			shared_cost numeric(15, 2),
			sctv_cost numeric(15, 2),
			update_user varchar(30),
			update_date timestamp(0),
			row_id varchar(18),
			org_lang_code varchar(2),
			home_cost numeric(15, 2),
			exp_runs numeric,
			note varchar(100),
			color_bw bpchar(1),
			stars_film varchar(254),
			co_stars varchar(254),
			directors varchar(254),
			producers varchar(254),
			"comments" varchar(254),
			grading varchar(100),
			use_restrictions varchar(100),
			target_aud varchar(100),
			made_for bpchar(1),
			actual_air_date timestamp(0),
			synopsis varchar(4000),
			insertmode varchar(1),
			seqno numeric,
			pattern_code varchar(10),
			bonus_code varchar(10),
			live_program bpchar(1),
			copycost bpchar(1),
			bannername varchar(40),
			film_poc varchar(9),
			row_id_poc varchar(18),
			exchange_code numeric,
			catsri_code varchar(3),
			catslot_code varchar(3),
			film_drama varchar(1),
			curr_code varchar(5),
			dist_code varchar(6),
			hold_lic_start timestamp(0),
			hold_lic_end timestamp(0),
			avail_start_date timestamp(0),
			avail_end_date timestamp(0),
			temp_programid varchar(10),
			pur_seqno numeric,
			is_series bpchar(1),
			nett_gross_flag bpchar(1),
			program_category varchar(3),
			pcountry_code varchar(3),
			life_long_rights varchar(1),
			unlimited_runs varchar(1),
			deal_type varchar(6),
			banner_ref varchar(60),
			web_link varchar(200),
			suffix varchar(5),
			start_no numeric,
			end_no numeric,
			prog_id numeric,
			film_title_old varchar(100),
			lic_end_date_temp varchar(10),
			lic_start_date_old varchar(10),
			prog_group varchar(2),
			num_of_episodes_po numeric,
			exp_runs_po numeric,
			sap_cost numeric(15, 2),
			budget_code varchar(100),
			sap_amor numeric(15, 2),
			run_repeat varchar(1),
			is_row_id varchar(18),
			subtitling varchar(1),
			channel_afi varchar(3),
			source_copy varchar(1),
			run_license_flag varchar(1),
			snp bpchar(1),
			schn_repeat bpchar(1),
			hours_repeat numeric,
			day_repeat numeric,
			max_repeat numeric,
			amor_type varchar(1),
			contract_ref_num varchar(30),
			sts_program bpchar(1),
			row_id_old varchar(18)
		)
with DATA
;
CREATE index idx_purchase_contract_dtl_row_id ON purchase_contract_dtl (row_id);
