DROP FOREIGN TABLE IF EXISTS st_pkg_int_hdr;

CREATE FOREIGN TABLE st_pkg_int_hdr (
	package_number varchar(30) OPTIONS(key 'true') NOT NULL,
	revision_no varchar(5) NOT NULL,
	package_type varchar(10) NOT NULL,
	pkg_name varchar(50) NOT NULL,
	pkg_desc varchar(100) NOT NULL,
	pkg_date timestamp(0) NOT NULL,
	currency varchar(5) NOT NULL,
	agency_code varchar(20) NULL,
	sales_code varchar(5) NULL,
	client_name varchar(20) NULL,
	approve_flag bpchar(1) NOT NULL,
	product_code varchar(20) NULL,
	approve_date timestamp(0) NULL,
	target_audience varchar(20) NULL,
	agen_approval_date timestamp(0) NULL,
	contract_no varchar(40) NULL,
	booking_per_from timestamp(0) NOT NULL,
	booking_per_to timestamp(0) NOT NULL,
	created_by varchar(20) NOT NULL,
	created_date timestamp(0) NOT NULL,
	rating_based_on bpchar(1) NOT NULL,
	remarks varchar(4000) NULL,
	foot_note varchar(4000) NULL,
	agency_approval bpchar(1) NOT NULL,
	package_remarks varchar(4000) NULL,
	package_gross_amt numeric(20, 5) NULL,
	other_cost1 numeric(20, 5) NULL,
	othercostavg1 bpchar(1) NOT NULL,
	other_cost2 numeric(20, 5) NULL,
	othercostavg2 bpchar(1) NOT NULL,
	other_cost3 numeric(20, 5) NULL,
	othercostavg3 bpchar(1) NOT NULL,
	refpackageno varchar(30) NULL,
	refpackagerowid varchar(30) NULL,
	update_user varchar(20) NOT NULL,
	update_date timestamp(0) NOT NULL,
	row_id varchar(20) NOT NULL,
	agency_approval_user varchar(20) NULL,
	billable bpchar(1) NULL,
	cash_disc_per numeric(5, 2) NULL,
	cash_disc_amt numeric(20, 2) NULL,
	package_int_amt numeric(20, 2) NULL,
	grossafterdisc numeric(20, 2) NULL,
	agen_comm numeric(5, 2) NULL,
	netpkgvalue numeric(20, 2) NULL,
	totalexternalgross numeric(20, 2) NULL,
	totalbonusamt numeric(20, 2) NULL,
	additionalbonusamt numeric(20, 2) NULL,
	totalpkgbonus numeric(20, 2) NULL,
	totalbonustaken numeric(20, 2) NULL,
	totalbalancebonus numeric(20, 2) NULL,
	cprpoffered numeric(20, 2) NULL,
	ratingta varchar(10) NULL,
	totalextnett numeric(20, 2) NULL,
	othercost1_desc varchar(50) NULL,
	othercost2_desc varchar(50) NULL,
	othercost3_desc varchar(50) NULL,
	prorata_per numeric(20, 2) NULL,
	totalnon_avgamt numeric(20, 2) NULL,
	ratingweekfrom timestamp(0) NULL,
	ratingweekto timestamp(0) NULL,
	extaftercomm numeric(20, 2) NULL,
	marginnett numeric(20, 2) NULL,
	othercost_flag bpchar(1) NULL,
	distri_date timestamp(0) NULL,
	cancel_flag bpchar(1) NULL,
	cancel_date timestamp(0) NULL,
	cancel_user varchar(20) NULL,
	revision_manual varchar(5) NULL,
	approve_user varchar(20) NULL,
	is_sponsor bpchar(1) NULL,
	manual_billing bpchar(1) NULL,
	sponsorship_temp_code varchar(20) NULL,
	final_apv1_flag varchar(1) NOT NULL,
	final_apv1_user varchar(10) NULL,
	final_apv1_date timestamp(0) NULL,
	final_apv1_pct numeric(7, 2) NULL,
	final_apv1_remarks varchar(100) NULL,
	final_apv2_flag varchar(1) NOT NULL,
	final_apv2_user varchar(10) NULL,
	final_apv2_date timestamp(0) NULL,
	final_apv2_pct numeric(7, 2) NULL,
	final_apv2_remarks varchar(100) NULL,
	man_ros_prorate_flag varchar(1) NOT NULL,
	man_ros_prorate_user varchar(10) NULL,
	man_ros_prorate_date timestamp(0) NULL,
	man_ros_prorate_amt numeric(15, 2) NULL,
	man_ros_prorate_remarks varchar(100) NULL,
	man_bns_prorate_flag varchar(1) NOT NULL,
	man_bns_prorate_user varchar(10) NULL,
	man_bns_prorate_date timestamp(0) NULL,
	man_bns_prorate_amt numeric(15, 2) NULL,
	man_bns_prorate_remarks varchar(100) NULL,
	man_ntc_prorate_flag varchar(1) NOT NULL,
	man_ntc_prorate_user varchar(10) NULL,
	man_ntc_prorate_date timestamp(0) NULL,
	man_ntc_prorate_amt numeric(15, 2) NULL,
	man_ntc_prorate_remarks varchar(100) NULL,
	is_link_pack varchar(1) NOT NULL,
	link_pack_no varchar(30) NULL,
	grp numeric(15, 2) NULL,
	client_grp numeric(15, 2) NULL,
	link_pack_com varchar(20) NULL,
	sub_agen_code varchar(20) NULL,
	alt_package_number varchar(30) NULL,
	man_rate_po_flag varchar(1) NOT NULL,
	man_rate_po_user varchar(10) NULL,
	man_rate_po_date timestamp(0) NULL,
	man_rate_po_remarks varchar(100) NULL,
	bonus_apv1_pct numeric(7, 2) NULL,
	bonus_apv2_pct numeric(7, 2) NULL,
	grp_00 numeric(15, 2) NULL,
	bonus_apv2_flag varchar(1) NOT NULL,
	bonus_apv1_date timestamp(0) NULL,
	bonus_apv1_remarks varchar(100) NULL,
	bonus_apv1_flag varchar(1) NOT NULL,
	bonus_apv2_date timestamp(0) NULL,
	bonus_apv2_remarks varchar(100) NULL,
	bonus_apv2_user varchar(10) NULL,
	bonus_apv1_user varchar(10) NULL,
	grp_program numeric(15, 2) NULL,
	inv_publisher varchar(5) NULL,
	history_per_from timestamp(0) NULL,
	history_per_to timestamp(0) NULL,
	flag_pdkt bpchar(1) NULL,
	prorate_lock bpchar(1) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'ST_PKG_INT_HDR');