DROP FOREIGN TABLE IF EXISTS tt_mo1;

CREATE FOREIGN TABLE tt_mo1 (
	row_id_spot varchar(18) OPTIONS(key 'true') NOT NULL,
	tx_time varchar(11) NULL,
	prod_code varchar(20) NULL,
	prod_version varchar(5) NULL,
	cb_seq numeric NULL,
	spot_seq numeric NULL,
	rate_code varchar(5) NULL,
	rate_amount numeric(15, 2) NULL,
	billed bpchar(1) NULL,
	verified bpchar(1) NULL,
	billed_date timestamp(0) NULL,
	verified_date timestamp(0) NULL,
	billed_user varchar(20) NULL,
	verified_user varchar(20) NULL,
	mo_book_date timestamp(0) NULL,
	mo_book_time varchar(8) NULL,
	syn_rate bpchar(1) NULL,
	syn_version bpchar(1) NULL,
	invoiced bpchar(1) NULL,
	ack_traffic bpchar(1) NULL,
	tx_time_fp varchar(8) NULL,
	update_date timestamp(0) NULL,
	update_user varchar(10) NULL,
	traffic_desc varchar(250) NULL,
	tr_user varchar(10) NULL,
	tr_date timestamp(0) NULL,
	ack_remark varchar(500) NULL,
	mo_no varchar(20) NULL,
	org_rate_code varchar(5) NULL,
	org_rate_amount numeric(15, 2) NULL,
	org_prod_version varchar(5) NULL,
	inv_cancel varchar(1) NULL,
	row_id_slot varchar(18) NULL,
	backup_no numeric NULL,
	row_id_backup varchar(20) NULL,
	verify_remarks varchar(300) NULL,
	flag_system varchar(1) NULL,
	act_film_poc varchar(9) NULL,
	act_row_id_poc varchar(18) NULL,
	act_cb_group_no numeric NULL,
	migration_data varchar(1) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'TT_MO2');