insert into master_tax_object (
	taxobjectid,
	name,
	created_date,
	is_disabled
)
values
('24-100-01', 'Hadiah, penghargaan, bonus dan lainnya selain yang telah dipotong PPh Pasal 21 ayat (1) huruf e UU PPh', now(), false),
('24-100-02', 'Sewa dan penghasilan lain sehubungan dengan penggunaan harta kecuali sewa tanah dan bangunan yang telah dikenai PPh Pasal 4 ayat (2) UU PPh', now(), false),
('24-101-01', 'Deviden tidak termasuk deviden kepada Wajib Pajak orang pribadi dalam negeri', now(), false),
('24-102-01', 'Bunga tidak termasuk bunga yang menjadi objek PPh Pasal 4 ayat (2)', now(), false),
('24-103-01', 'Royalti', now(), false),
('24-104-01', 'Jasa Teknik', now(), false),
('24-104-02', 'Jasa Management', now(), false),
('24-104-03', 'Jasa Konsultan', now(), false),
('24-104-04', 'Jasa penilai (appraisal) ', now(), false),
('24-104-05', 'Jasa aktuaris ', now(), false),
('24-104-06', 'Jasa akuntansi, pembukuan, dan atestasi laporan keuangan', now(), false),
('24-104-07', 'Jasa hukum', now(), false),
('24-104-08', 'Jasa arsitektur', now(), false),
('24-104-09', 'Jasa perencanaan kota dan arsitektur landscape ', now(), false),
('24-104-10', 'Jasa perancang (design) ', now(), false),
('24-104-11', 'Jasa pengeboran (drilling) di bidang penambangan minyak dan gas bumi (migas) kecuali yang dilakukan oleh Badan Usaha Tetap (BUT) ', now(), false),
('24-104-12', 'Jasa penunjang di bidang usaha panas bumi dan penambangan minyak dan gas bumi (migas) ', now(), false),
('24-104-13', 'Jasa penambangan dan jasa penunjang di bidang usaha panas bumi dan penambangan minyak dan gas bumi (migas) ', now(), false),
('24-104-14', 'Jasa penunjang di bidang penerbangan dan bandar udara ', now(), false),
('24-104-15', 'Jasa penebangan hutan', now(), false),
('24-104-16', 'Jasa pengolahan limbah ', now(), false),
('24-104-17', 'Jasa penyedia tenaga kerja dan/atau tenaga ahli (outsourcing services)', now(), false),
('24-104-18', 'Jasa perantara dan/atau keagenan ', now(), false),
('24-104-19', 'Jasa bidang perdagangan surat-surat berharga, kecuali yang dilakukan Bursa Efek, Kustodian Sentral Efek Indonesia (KSEI) dan Kliring Penjaminan Efek Indonesia (KPEI)', now(), false),
('24-104-20', 'Jasa kustodian/penyimpanan/penitipan, kecuali yang dilakukan oleh KSEI', now(), false),
('24-104-21', 'Jasa pengisian suara (dubbing) dan/atau sulih suara', now(), false),
('24-104-22', 'Jasa mixing film', now(), false),
('24-104-23', 'Jasa pembuatan sarana promosi film, iklan, poster, foto, slide, klise, banner, pamphlet, baliho dan folder', now(), false),
('24-104-24', 'Jasa sehubungan dengan software atau hardware atau sistem komputer, termasuk perawatan, pemeliharaan dan perbaikan. ', now(), false),
('24-104-25', 'Jasa pembuatan dan/atau pengelolaan website', now(), false),
('24-104-26', 'Jasa internet termasuk sambungannya', now(), false),
('24-104-27', 'Jasa penyimpanan, pengolahan dan/atau penyaluran data, informasi, dan/atau program', now(), false),
('24-104-28', 'Jasa instalasi/pemasangan mesin, peralatan, listrik, telepon, air, gas, AC dan/atau TV Kabel, selain yang dilakukan oleh Wajib Pajak yang ruang lingkupnya di bidang konstruksi dan mempunyai izin dan/atau sertifikasi sebagai pengusaha konstruksi', now(), false),
('24-104-29', 'Jasa perawatan/perbaikan/pemeliharaan mesin, peralatan, listrik, telepon, air, gas, AC dan/atau TV kabel, selain yang dilakukan oleh Wajib Pajak yang ruang lingkupnya di bidang konstruksi dan mempunyai izin dan/atau sertifikasi sebagai pengusaha konstruksi', now(), false),
('24-104-30', 'Jasa perawatan kendaraan dan/atau alat transportasi darat', now(), false),
('24-104-31', 'Jasa maklon', now(), false),
('24-104-32', 'Jasa penyelidikan dan keamanan', now(), false),
('24-104-33', 'Jasa penyelenggara kegiatan atau event organizer', now(), false),
('24-104-34', 'Jasa penyediaan tempat dan/atau waktu dalam media massa, media luar ruang atau media lain untuk penyampaian informasi, dan/atau jasa periklanan', now(), false),
('24-104-35', 'Jasa pembasmian hama', now(), false),
('24-104-36', 'Jasa kebersihan atau cleaning service', now(), false),
('24-104-37', 'Jasa sedot septic tank', now(), false),
('24-104-38', 'Jasa pemeliharaan kolam', now(), false),
('24-104-39', 'Jasa katering atau tata boga', now(), false),
('24-104-40', 'Jasa freight forwarding', now(), false),
('24-104-41', 'Jasa logistik', now(), false),
('24-104-42', 'Jasa pengurusan dokumen', now(), false),
('24-104-43', 'Jasa pengepakan', now(), false),
('24-104-44', 'Jasa loading dan unloading', now(), false),
('24-104-45', 'Jasa laboratorium dan/atau pengujian kecuali yang dilakukan oleh lembaga atau institusi pendidikan dalam rangka penelitian akademis', now(), false),
('24-104-46', 'Jasa pengelolaan parkir', now(), false),
('24-104-47', 'Jasa penyondiran tanah', now(), false),
('24-104-48', 'Jasa penyiapan dan/atau pengolahan lahan', now(), false),
('24-104-49', 'Jasa pembibitan dan/atau penanaman bibit', now(), false),
('24-104-50', 'Jasa pemeliharaan tanaman', now(), false),
('24-104-51', 'Jasa permanenan', now(), false),
('24-104-52', 'Jasa pengolahan hasil pertanian, perkebunan, perikanan, peternakan dan/atau perhutanan', now(), false),
('24-104-53', 'Jasa dekorasi', now(), false),
('24-104-54', 'Jasa pencetakan/penerbitan', now(), false),
('24-104-55', 'Jasa penerjemahan', now(), false),
('24-104-56', 'Jasa pengangkutan/ekspedisi kecuali yang telah diatur dalam Pasal 15 Undang-Undang Pajak Penghasilan', now(), false),
('24-104-57', 'Jasa pelayanan pelabuhan', now(), false),
('24-104-58', 'Jasa pengangkutan melalui jalur pipa', now(), false),
('24-104-59', 'Jasa pengelolaan penitipan anak', now(), false),
('24-104-60', 'Jasa pelatihan dan/atau kursus', now(), false),
('24-104-61', 'Jasa pengiriman dan pengisian uang ke ATM', now(), false),
('24-104-62', 'Jasa sertifikasi', now(), false),
('24-104-63', 'Jasa survey', now(), false),
('24-104-64', 'Jasa tester', now(), false),
('24-104-65', 'Jasa selain jasa-jasa tersebut di atas yang pembayarannya dibebankan pada APBN (Anggaran Pendapatan dan Belanja Negara) atau APBD (Anggaran Pendapatan dan Belanja Daerah).', now(), false),
('27-100-01', 'Sewa dan penghasilan lain sehubungan dengan penggunaan harta', now(), false),
('27-100-02', 'Hadiah dan penghargaan', now(), false),
('27-100-03', 'Pensiun dan pembayaran berkala lainnya', now(), false),
('27-100-04', 'Keuntungan karena pembebasan utang', now(), false),
('27-100-05', 'Penjualan / pengalihan harta di Indonesia', now(), false),
('27-100-06', 'Premi asuransi / reasuransi', now(), false),
('27-100-07', 'Penghasilan dari penjualan atau pengalihan saham', now(), false),
('27-101-01', 'Deviden', now(), false),
('27-102-01', 'Bunga', now(), false),
('27-102-02', 'Premi swap atau transaksi lindung lainnya', now(), false),
('27-103-01', 'Royalti', now(), false),
('27-104-01', 'Imbalan sehubungan dengan jasa, pekerjaan dan kegiatan', now(), false),
('27-105-01', 'Penghasilan Kena Pajak BUT setelah pajak', now(), false),
('28-423-01', 'Transaksi dengan WP yang menggunakan tarif PP 23 Tahun 2018', now(), false)
;
