insert into relation_hris_inventory_department values('B1A', 'ACC', 'ACCOUNTING DEPARTMENT');
insert into relation_hris_inventory_department values('B1C', 'ACC', 'ACCOUNTING DEPARTMENT');
insert into relation_hris_inventory_department values('B1C', 'BMA', 'BUDGET MANAGEMENT ACCOUNTING');
insert into relation_hris_inventory_department values('D3B', 'ARP', 'ART PROPERTY');
insert into relation_hris_inventory_department values('D3B', 'ART', 'ART DEPARTMENT');
insert into relation_hris_inventory_department values('D3B', 'ARW', 'WARDROBE');
--insert into relation_hris_inventory_department values(NULL, 'BDE', 'BUSSINESS DEVELOPMENT');
insert into relation_hris_inventory_department values('B2A', 'BEN', 'BUILDING ENGINEERING DEPARTMENT');
insert into relation_hris_inventory_department values('SC000121', 'BPM', 'BUSINESS PROCESS MANAGEMENT');
insert into relation_hris_inventory_department values('SC000123', 'BPM', 'BUSINESS PROCESS MANAGEMENT');
insert into relation_hris_inventory_department values('G1A', 'BPM', 'BUSINESS PROCESS MANAGEMENT');
--insert into relation_hris_inventory_department values(NULL, 'CIA', 'COMPLIANCE & INTERNAL AUDITING');
--insert into relation_hris_inventory_department values(NULL, 'CSL', 'CORPORATE SECRETARY & LEGAL');
insert into relation_hris_inventory_department values('F1A', 'CTR', 'COMMERCIAL TRAFFIC DEPARTMENT');
insert into relation_hris_inventory_department values('F3A', 'CTR', 'COMMERCIAL TRAFFIC DEPARTMENT');
insert into relation_hris_inventory_department values('B1D', 'FHR', 'FINANCE & HUMAN RESOURCES DIRECTOR');
insert into relation_hris_inventory_department values('B2B', 'FHR', 'FINANCE & HUMAN RESOURCES DIRECTOR');
insert into relation_hris_inventory_department values('B1D', 'FNC', 'FINANCE DEPARTMENT');
insert into relation_hris_inventory_department values('B2A', 'GSV', 'GENERAL SERVICES DEPARTMENT');
insert into relation_hris_inventory_department values('B2C', 'HCO', 'HUMAN CAPITAL OPERATION DEPARTMENT');
insert into relation_hris_inventory_department values('E1A', 'ITE', 'IT DEPARTMENT');
--insert into relation_hris_inventory_department values(NULL, 'KOM', 'KOMISARIS');
--insert into relation_hris_inventory_department values(NULL, 'KUT', 'KOMISARIS UTAMA');
insert into relation_hris_inventory_department values('G1B', 'LEG', 'LEGAL');
insert into relation_hris_inventory_department values('C1A', 'NWS', 'NEWS');
insert into relation_hris_inventory_department values('C1C', 'NWS', 'NEWS');
insert into relation_hris_inventory_department values('C1E', 'NWS', 'NEWS');
insert into relation_hris_inventory_department values('D1H', 'OPR', 'OPERATIONS DEPARTMENT');
--insert into relation_hris_inventory_department values(NULL, 'PCD', 'PRODUCTION CREATIVE DEVELOPMENT CENTER');
--insert into relation_hris_inventory_department values(NULL, 'PDI', 'PRESIDENT DIRECTOR');
insert into relation_hris_inventory_department values('E1B', 'POV', 'PROGRAM OPERATION');
insert into relation_hris_inventory_department values('E2A', 'POV', 'PROGRAM OPERATION');
insert into relation_hris_inventory_department values('E2B', 'POV', 'PROGRAM OPERATION');
insert into relation_hris_inventory_department values('D1B', 'PRD', 'PRODUCTION');
insert into relation_hris_inventory_department values('D1C', 'PRD', 'PRODUCTION');
insert into relation_hris_inventory_department values('D1D', 'PRD', 'PRODUCTION');
insert into relation_hris_inventory_department values('D1F', 'PRD', 'PRODUCTION');
insert into relation_hris_inventory_department values('D1H', 'PRD', 'PRODUCTION');
insert into relation_hris_inventory_department values('F2A', 'PRE', 'PUBLIC RELATION');
insert into relation_hris_inventory_department values('F3B', 'PRM', 'PROMOTION DEPARTMENT');
insert into relation_hris_inventory_department values('G1C', 'PRO', 'PROCUREMENT');
insert into relation_hris_inventory_department values('D3D', 'PSV', 'PRODUCTION SERVICES DEPARTMENT');
insert into relation_hris_inventory_department values('F4A', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F4B', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F4C', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F5D', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F5E', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F5F', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F8A', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F8B', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('F8C', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('SC000113', 'SLS', 'SALES DEPARTEMENT');
insert into relation_hris_inventory_department values('D3C', 'TOA', 'TECHNICAL ON AIR DEPARTMENT');
insert into relation_hris_inventory_department values('E1C', 'TRM', 'TRANSMISSION DEPARTMENT');
insert into relation_hris_inventory_department values('D3C', 'TSV', 'TECHNICAL SERVICES DEPARTMENT');
insert into relation_hris_inventory_department values('TV7', 'TV7', 'TV7');
