DROP MATERIALIZED VIEW IF EXISTS mt_prod1 cascade;

CREATE materialized VIEW mt_prod1 as
	SELECT 
		prod_code,
		prod_version,
		prod_version_name,
		prod_duration,
		prod_som,
		prod_eom,
		schobj_code,
		house_no,
		machine_code,
		prod_vclip,
		prod_expired,
		prod_censor,
		prod_censord,
		prod_censore,
		material_code,
		prod_remark,
		non_active,
		update_user,
		update_date,
		row_id,
		prod_duration_s,
		prod_duration_f,
		old_rec,
		filepath,
		client_code,
		sales_code,
		returned,
		cut_no,
		master_copy_no,
		start_date,
		seg_in_tape,
		in_server,
		row_id_mversion,
		is_mversion,
		video_path,
		dateingest,
		datereturned,
		dateserverdelete,
		pathname,
		housenolink,
		agen_code,
		revision_no,
		revision_remarks,
		run_code,
		schobj_time,
		tapedur,
		old_prod_version,
		copy_prod_code,
		copy_prod_version,
		entry_date,
		entry_user,
		material_dur,
		new_row,
		flag_receive,
		date_receive,
		qc_status,
		flag_suspend,
		date_suspend_from,
		date_suspend_to,
		hd_sd_flag,
		frame_rate,
		lang_code,
		qc_user,
		qc_date,
		qc_trans_status,
		qc_trans_user,
		qc_trans_date,
		qc_tech_status,
		qc_tech_user,
		qc_tech_date,
		snp_required,
		prod_version_alt_name,
		qc_from,
		qc_trans_from,
		qc_tech_from,
		file_ext,
		audio_ext,
		receiveform_sign,
		salesmanager_sign
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					prod_code,
					prod_version,
					prod_version_name,
					prod_duration,
					prod_som,
					prod_eom,
					schobj_code,
					house_no,
					machine_code,
					prod_vclip,
					prod_expired,
					prod_censor,
					prod_censord,
					prod_censore,
					material_code,
					prod_remark,
					non_active,
					update_user,
					update_date,
					row_id,
					prod_duration_s,
					prod_duration_f,
					old_rec,
					filepath,
					client_code,
					sales_code,
					returned,
					cut_no,
					master_copy_no,
					start_date,
					seg_in_tape,
					in_server,
					row_id_mversion,
					is_mversion,
					video_path,
					dateingest,
					datereturned,
					dateserverdelete,
					pathname,
					housenolink,
					agen_code,
					revision_no,
					revision_remarks,
					run_code,
					schobj_time,
					tapedur,
					old_prod_version,
					copy_prod_code,
					copy_prod_version,
					entry_date,
					entry_user,
					material_dur,
					new_row,
					flag_receive,
					date_receive,
					qc_status,
					flag_suspend,
					date_suspend_from,
					date_suspend_to,
					hd_sd_flag,
					frame_rate,
					lang_code,
					qc_user,
					qc_date,
					qc_trans_status,
					qc_trans_user,
					qc_trans_date,
					qc_tech_status,
					qc_tech_user,
					qc_tech_date,
					snp_required,
					prod_version_alt_name,
					qc_from,
					qc_trans_from,
					qc_tech_from,
					file_ext,
					audio_ext,
					receiveform_sign,
					salesmanager_sign
				FROM gen21.mt_prod1
			'
   		) tbl(
			prod_code varchar(20),
			prod_version varchar(5),
			prod_version_name varchar(50),
			prod_duration varchar(8),
			prod_som varchar(8),
			prod_eom varchar(8),
			schobj_code varchar(5),
			house_no varchar(100),
			machine_code varchar(5),
			prod_vclip bpchar(1),
			prod_expired timestamp(0),
			prod_censor varchar(30),
			prod_censord timestamp(0),
			prod_censore timestamp(0),
			material_code varchar(3),
			prod_remark varchar(1000),
			non_active timestamp(0),
			update_user varchar(10),
			update_date timestamp(0),
			row_id varchar(18),
			prod_duration_s int4,
			prod_duration_f int2,
			old_rec bpchar(1),
			filepath varchar(4000),
			client_code varchar(20),
			sales_code varchar(5),
			returned bpchar(1),
			cut_no varchar(10),
			master_copy_no varchar(50),
			start_date timestamp(0),
			seg_in_tape varchar(4),
			in_server varchar(1),
			row_id_mversion varchar(18),
			is_mversion bpchar(1),
			video_path varchar(4000),
			dateingest timestamp(0),
			datereturned timestamp(0),
			dateserverdelete timestamp(0),
			pathname varchar(4000),
			housenolink varchar(100),
			agen_code varchar(20),
			revision_no numeric,
			revision_remarks varchar(500),
			run_code varchar(6),
			schobj_time bpchar(1),
			tapedur varchar(8),
			old_prod_version varchar(5),
			copy_prod_code varchar(20),
			copy_prod_version varchar(5),
			entry_date timestamp(0),
			entry_user varchar(20),
			material_dur varchar(8),
			new_row bpchar(1),
			flag_receive bpchar(1),
			date_receive timestamp(0),
			qc_status bpchar(1),
			flag_suspend bpchar(1),
			date_suspend_from timestamp(0),
			date_suspend_to timestamp(0),
			hd_sd_flag varchar(2),
			frame_rate numeric,
			lang_code varchar(2),
			qc_user varchar(200),
			qc_date timestamp(0),
			qc_trans_status bpchar(1),
			qc_trans_user varchar(200),
			qc_trans_date timestamp(0),
			qc_tech_status bpchar(1),
			qc_tech_user varchar(200),
			qc_tech_date timestamp(0),
			snp_required bpchar(1),
			prod_version_alt_name varchar(100),
			qc_from varchar(1),
			qc_trans_from varchar(1),
			qc_tech_from varchar(1),
			file_ext varchar(10),
			audio_ext varchar(10),
			receiveform_sign bpchar(1),
			salesmanager_sign bpchar(1)
		)
with DATA
;
CREATE index idx_mt_prod1_custom1 ON mt_prod1 (prod_code, prod_version);
