DROP MATERIALIZED VIEW IF EXISTS purchase_contract_hdr cascade;

CREATE materialized VIEW purchase_contract_hdr as
	SELECT 
		pur_contract_no,
		revision_no,
		pur_pkg_name,
		distri_code,
		pur_contract_date,
		buyer,
		control_leg_num,
		contract_ref_num,
		first_air_date,
		lic_in_yrs_months,
		contract_start_date,
		contract_end_date,
		number_of_runs,
		program_type,
		program_category,
		material_to_be_shipped,
		num_of_episodes,
		actual_air_date,
		other_requirements,
		currency_id,
		total_original_cost,
		total_episodes,
		total_sharedcost,
		total_hours,
		any_exception,
		explanation,
		buyer_person_name,
		buying_date,
		ack_by,
		ack_date,
		revision_source,
		pur_type,
		approved,
		remarks,
		update_user,
		update_date,
		row_id,
		live_program,
		live_sch_date,
		revision_desc,
		is_series,
		home_cost,
		delivery_material,
		payment_terms,
		lic_in_months,
		promo_material_flag,
		po_sub_grp,
		channel_code,
		life_long_rights,
		playspertitle,
		exchange_rate,
		renewal,
		pur_date_upld,
		temp_purcont_date,
		pur_seqno,
		cancel_date,
		sts_cancel,
		bkp_sb_grp,
		ctr_org_cost,
		ctr_home_cost,
		created_date,
		sch_flag,
		cancel_remarks,
		revision_no_new,
		revise_remarks,
		pur_pkg_name_old,
		contract_ref_old,
		contract_start_date_old,
		contract_end_date_old,
		pur_contract_date_old,
		created_date_old,
		update_date_old,
		lic_type,
		"owner",
		pur_type_old,
		fix_rate_flag,
		add_region_f,
		agen_code,
		is_row_id,
		po_type,
		distri_ref,
		distri_code_org,
		pcountry_name,
		pcountry_code,
		row_id_old,
		sts_adj
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					pur_contract_no,
					revision_no,
					pur_pkg_name,
					distri_code,
					pur_contract_date,
					buyer,
					control_leg_num,
					contract_ref_num,
					first_air_date,
					lic_in_yrs_months,
					contract_start_date,
					contract_end_date,
					number_of_runs,
					program_type,
					program_category,
					material_to_be_shipped,
					num_of_episodes,
					actual_air_date,
					other_requirements,
					currency_id,
					total_original_cost,
					total_episodes,
					total_sharedcost,
					total_hours,
					any_exception,
					explanation,
					buyer_person_name,
					buying_date,
					ack_by,
					ack_date,
					revision_source,
					pur_type,
					approved,
					remarks,
					update_user,
					update_date,
					row_id,
					live_program,
					live_sch_date,
					revision_desc,
					is_series,
					home_cost,
					delivery_material,
					payment_terms,
					lic_in_months,
					promo_material_flag,
					po_sub_grp,
					channel_code,
					life_long_rights,
					playspertitle,
					exchange_rate,
					renewal,
					pur_date_upld,
					temp_purcont_date,
					pur_seqno,
					cancel_date,
					sts_cancel,
					bkp_sb_grp,
					ctr_org_cost,
					ctr_home_cost,
					created_date,
					sch_flag,
					cancel_remarks,
					revision_no_new,
					revise_remarks,
					pur_pkg_name_old,
					contract_ref_old,
					contract_start_date_old,
					contract_end_date_old,
					pur_contract_date_old,
					created_date_old,
					update_date_old,
					lic_type,
					"owner",
					pur_type_old,
					fix_rate_flag,
					add_region_f,
					agen_code,
					is_row_id,
					po_type,
					distri_ref,
					distri_code_org,
					pcountry_name,
					pcountry_code,
					row_id_old,
					sts_adj
				FROM gen21.purchase_contract_hdr
			'
   		) tbl(
			pur_contract_no varchar(30),
			revision_no numeric,
			pur_pkg_name varchar(200),
			distri_code varchar(6),
			pur_contract_date timestamp(0),
			buyer varchar(30),
			control_leg_num varchar(30),
			contract_ref_num varchar(30),
			first_air_date timestamp(0),
			lic_in_yrs_months numeric,
			contract_start_date timestamp(0),
			contract_end_date timestamp(0),
			number_of_runs numeric,
			program_type varchar(4),
			program_category varchar(3),
			material_to_be_shipped varchar(10),
			num_of_episodes numeric,
			actual_air_date timestamp(0),
			other_requirements varchar(30),
			currency_id varchar(4),
			total_original_cost numeric(15, 2),
			total_episodes numeric,
			total_sharedcost numeric(15, 2),
			total_hours numeric,
			any_exception bpchar(1),
			explanation varchar(100),
			buyer_person_name varchar(30),
			buying_date timestamp(0),
			ack_by varchar(30),
			ack_date timestamp(0),
			revision_source numeric,
			pur_type varchar(6),
			approved bpchar(1),
			remarks varchar(4000),
			update_user varchar(30),
			update_date timestamp(0),
			row_id varchar(18),
			live_program bpchar(1),
			live_sch_date timestamp(0),
			revision_desc varchar(250),
			is_series bpchar(1),
			home_cost numeric,
			delivery_material varchar(50),
			payment_terms varchar(100),
			lic_in_months numeric,
			promo_material_flag bpchar(1),
			po_sub_grp varchar(6),
			channel_code varchar(3),
			life_long_rights varchar(1),
			playspertitle numeric,
			exchange_rate numeric,
			renewal numeric,
			pur_date_upld varchar(10),
			temp_purcont_date varchar(10),
			pur_seqno numeric,
			cancel_date timestamp(0),
			sts_cancel bpchar(1),
			bkp_sb_grp varchar(10),
			ctr_org_cost numeric(15, 2),
			ctr_home_cost numeric(15, 2),
			created_date timestamp(0),
			sch_flag bpchar(1),
			cancel_remarks varchar(4000),
			revision_no_new numeric,
			revise_remarks varchar(4000),
			pur_pkg_name_old varchar(200),
			contract_ref_old varchar(100),
			contract_start_date_old varchar(10),
			contract_end_date_old varchar(10),
			pur_contract_date_old varchar(10),
			created_date_old varchar(10),
			update_date_old varchar(10),
			lic_type varchar(3),
			"owner" varchar(3),
			pur_type_old varchar(6),
			fix_rate_flag bpchar(1),
			add_region_f bpchar(1),
			agen_code varchar(20),
			is_row_id varchar(18),
			po_type varchar(6),
			distri_ref varchar(6),
			distri_code_org varchar(6),
			pcountry_name varchar(40),
			pcountry_code varchar(3),
			row_id_old varchar(18),
			sts_adj varchar(1)
		)
with DATA
;
CREATE index idx_purchase_contract_hdr_custom1 ON purchase_contract_hdr (revision_no, pur_contract_no);
