DROP MATERIALIZED VIEW IF EXISTS st_pkg_int_hdr cascade;

CREATE materialized VIEW st_pkg_int_hdr as
	SELECT 
		package_number,
		revision_no,
		package_type,
		pkg_name,
		pkg_desc,
		pkg_date,
		currency,
		agency_code,
		sales_code,
		client_name,
		approve_flag,
		product_code,
		approve_date,
		target_audience,
		agen_approval_date,
		contract_no,
		booking_per_from,
		booking_per_to,
		created_by,
		created_date,
		rating_based_on,
		remarks,
		foot_note,
		agency_approval,
		package_remarks,
		package_gross_amt,
		other_cost1,
		othercostavg1,
		other_cost2,
		othercostavg2,
		other_cost3,
		othercostavg3,
		refpackageno,
		refpackagerowid,
		update_user,
		update_date,
		row_id,
		agency_approval_user,
		billable,
		cash_disc_per,
		cash_disc_amt,
		package_int_amt,
		grossafterdisc,
		agen_comm,
		netpkgvalue,
		totalexternalgross,
		totalbonusamt,
		additionalbonusamt,
		totalpkgbonus,
		totalbonustaken,
		totalbalancebonus,
		cprpoffered,
		ratingta,
		totalextnett,
		othercost1_desc,
		othercost2_desc,
		othercost3_desc,
		prorata_per,
		totalnon_avgamt,
		ratingweekfrom,
		ratingweekto,
		extaftercomm,
		marginnett,
		othercost_flag,
		distri_date,
		cancel_flag,
		cancel_date,
		cancel_user,
		revision_manual,
		approve_user,
		is_sponsor,
		manual_billing,
		sponsorship_temp_code,
		final_apv1_flag,
		final_apv1_user,
		final_apv1_date,
		final_apv1_pct,
		final_apv1_remarks,
		final_apv2_flag,
		final_apv2_user,
		final_apv2_date,
		final_apv2_pct,
		final_apv2_remarks,
		man_ros_prorate_flag,
		man_ros_prorate_user,
		man_ros_prorate_date,
		man_ros_prorate_amt,
		man_ros_prorate_remarks,
		man_bns_prorate_flag,
		man_bns_prorate_user,
		man_bns_prorate_date,
		man_bns_prorate_amt,
		man_bns_prorate_remarks,
		man_ntc_prorate_flag,
		man_ntc_prorate_user,
		man_ntc_prorate_date,
		man_ntc_prorate_amt,
		man_ntc_prorate_remarks,
		is_link_pack,
		link_pack_no,
		grp,
		client_grp,
		link_pack_com,
		sub_agen_code,
		alt_package_number,
		man_rate_po_flag,
		man_rate_po_user,
		man_rate_po_date,
		man_rate_po_remarks,
		bonus_apv1_pct,
		bonus_apv2_pct,
		grp_00,
		bonus_apv2_flag,
		bonus_apv1_date,
		bonus_apv1_remarks,
		bonus_apv1_flag,
		bonus_apv2_date,
		bonus_apv2_remarks,
		bonus_apv2_user,
		bonus_apv1_user,
		grp_program,
		inv_publisher,
		history_per_from,
		history_per_to,
		flag_pdkt,
		prorate_lock
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					package_number,
					revision_no,
					package_type,
					pkg_name,
					pkg_desc,
					pkg_date,
					currency,
					agency_code,
					sales_code,
					client_name,
					approve_flag,
					product_code,
					approve_date,
					target_audience,
					agen_approval_date,
					contract_no,
					booking_per_from,
					booking_per_to,
					created_by,
					created_date,
					rating_based_on,
					remarks,
					foot_note,
					agency_approval,
					package_remarks,
					package_gross_amt,
					other_cost1,
					othercostavg1,
					other_cost2,
					othercostavg2,
					other_cost3,
					othercostavg3,
					refpackageno,
					refpackagerowid,
					update_user,
					update_date,
					row_id,
					agency_approval_user,
					billable,
					cash_disc_per,
					cash_disc_amt,
					package_int_amt,
					grossafterdisc,
					agen_comm,
					netpkgvalue,
					totalexternalgross,
					totalbonusamt,
					additionalbonusamt,
					totalpkgbonus,
					totalbonustaken,
					totalbalancebonus,
					cprpoffered,
					ratingta,
					totalextnett,
					othercost1_desc,
					othercost2_desc,
					othercost3_desc,
					prorata_per,
					totalnon_avgamt,
					ratingweekfrom,
					ratingweekto,
					extaftercomm,
					marginnett,
					othercost_flag,
					distri_date,
					cancel_flag,
					cancel_date,
					cancel_user,
					revision_manual,
					approve_user,
					is_sponsor,
					manual_billing,
					sponsorship_temp_code,
					final_apv1_flag,
					final_apv1_user,
					final_apv1_date,
					final_apv1_pct,
					final_apv1_remarks,
					final_apv2_flag,
					final_apv2_user,
					final_apv2_date,
					final_apv2_pct,
					final_apv2_remarks,
					man_ros_prorate_flag,
					man_ros_prorate_user,
					man_ros_prorate_date,
					man_ros_prorate_amt,
					man_ros_prorate_remarks,
					man_bns_prorate_flag,
					man_bns_prorate_user,
					man_bns_prorate_date,
					man_bns_prorate_amt,
					man_bns_prorate_remarks,
					man_ntc_prorate_flag,
					man_ntc_prorate_user,
					man_ntc_prorate_date,
					man_ntc_prorate_amt,
					man_ntc_prorate_remarks,
					is_link_pack,
					link_pack_no,
					grp,
					client_grp,
					link_pack_com,
					sub_agen_code,
					alt_package_number,
					man_rate_po_flag,
					man_rate_po_user,
					man_rate_po_date,
					man_rate_po_remarks,
					bonus_apv1_pct,
					bonus_apv2_pct,
					grp_00,
					bonus_apv2_flag,
					bonus_apv1_date,
					bonus_apv1_remarks,
					bonus_apv1_flag,
					bonus_apv2_date,
					bonus_apv2_remarks,
					bonus_apv2_user,
					bonus_apv1_user,
					grp_program,
					inv_publisher,
					history_per_from,
					history_per_to,
					flag_pdkt,
					prorate_lock
				FROM gen21.st_pkg_int_hdr
			'
   		) tbl(
			package_number varchar(30),
			revision_no varchar(5),
			package_type varchar(10),
			pkg_name varchar(50),
			pkg_desc varchar(100),
			pkg_date timestamp(0),
			currency varchar(5),
			agency_code varchar(20),
			sales_code varchar(5),
			client_name varchar(20),
			approve_flag bpchar(1),
			product_code varchar(20),
			approve_date timestamp(0),
			target_audience varchar(20),
			agen_approval_date timestamp(0),
			contract_no varchar(40),
			booking_per_from timestamp(0),
			booking_per_to timestamp(0),
			created_by varchar(20),
			created_date timestamp(0),
			rating_based_on bpchar(1),
			remarks varchar(4000),
			foot_note varchar(4000),
			agency_approval bpchar(1),
			package_remarks varchar(4000),
			package_gross_amt numeric(20, 5),
			other_cost1 numeric(20, 5),
			othercostavg1 bpchar(1),
			other_cost2 numeric(20, 5),
			othercostavg2 bpchar(1),
			other_cost3 numeric(20, 5),
			othercostavg3 bpchar(1),
			refpackageno varchar(30),
			refpackagerowid varchar(30),
			update_user varchar(20),
			update_date timestamp(0),
			row_id varchar(20),
			agency_approval_user varchar(20),
			billable bpchar(1),
			cash_disc_per numeric(5, 2),
			cash_disc_amt numeric(20, 2),
			package_int_amt numeric(20, 2),
			grossafterdisc numeric(20, 2),
			agen_comm numeric(5, 2),
			netpkgvalue numeric(20, 2),
			totalexternalgross numeric(20, 2),
			totalbonusamt numeric(20, 2),
			additionalbonusamt numeric(20, 2),
			totalpkgbonus numeric(20, 2),
			totalbonustaken numeric(20, 2),
			totalbalancebonus numeric(20, 2),
			cprpoffered numeric(20, 2),
			ratingta varchar(10),
			totalextnett numeric(20, 2),
			othercost1_desc varchar(50),
			othercost2_desc varchar(50),
			othercost3_desc varchar(50),
			prorata_per numeric(20, 2),
			totalnon_avgamt numeric(20, 2),
			ratingweekfrom timestamp(0),
			ratingweekto timestamp(0),
			extaftercomm numeric(20, 2),
			marginnett numeric(20, 2),
			othercost_flag bpchar(1),
			distri_date timestamp(0),
			cancel_flag bpchar(1),
			cancel_date timestamp(0),
			cancel_user varchar(20),
			revision_manual varchar(5),
			approve_user varchar(20),
			is_sponsor bpchar(1),
			manual_billing bpchar(1),
			sponsorship_temp_code varchar(20),
			final_apv1_flag varchar(1),
			final_apv1_user varchar(10),
			final_apv1_date timestamp(0),
			final_apv1_pct numeric(7, 2),
			final_apv1_remarks varchar(100),
			final_apv2_flag varchar(1),
			final_apv2_user varchar(10),
			final_apv2_date timestamp(0),
			final_apv2_pct numeric(7, 2),
			final_apv2_remarks varchar(100),
			man_ros_prorate_flag varchar(1),
			man_ros_prorate_user varchar(10),
			man_ros_prorate_date timestamp(0),
			man_ros_prorate_amt numeric(15, 2),
			man_ros_prorate_remarks varchar(100),
			man_bns_prorate_flag varchar(1),
			man_bns_prorate_user varchar(10),
			man_bns_prorate_date timestamp(0),
			man_bns_prorate_amt numeric(15, 2),
			man_bns_prorate_remarks varchar(100),
			man_ntc_prorate_flag varchar(1),
			man_ntc_prorate_user varchar(10),
			man_ntc_prorate_date timestamp(0),
			man_ntc_prorate_amt numeric(15, 2),
			man_ntc_prorate_remarks varchar(100),
			is_link_pack varchar(1),
			link_pack_no varchar(30),
			grp numeric(15, 2),
			client_grp numeric(15, 2),
			link_pack_com varchar(20),
			sub_agen_code varchar(20),
			alt_package_number varchar(30),
			man_rate_po_flag varchar(1),
			man_rate_po_user varchar(10),
			man_rate_po_date timestamp(0),
			man_rate_po_remarks varchar(100),
			bonus_apv1_pct numeric(7, 2),
			bonus_apv2_pct numeric(7, 2),
			grp_00 numeric(15, 2),
			bonus_apv2_flag varchar(1),
			bonus_apv1_date timestamp(0),
			bonus_apv1_remarks varchar(100),
			bonus_apv1_flag varchar(1),
			bonus_apv2_date timestamp(0),
			bonus_apv2_remarks varchar(100),
			bonus_apv2_user varchar(10),
			bonus_apv1_user varchar(10),
			grp_program numeric(15, 2),
			inv_publisher varchar(5),
			history_per_from timestamp(0),
			history_per_to timestamp(0),
			flag_pdkt bpchar(1),
			prorate_lock bpchar(1)
		)
with DATA
;
CREATE index idx_st_pkg_int_hdr_row_id ON st_pkg_int_hdr (row_id);
