DROP FOREIGN TABLE IF EXISTS st_reservations;

CREATE FOREIGN TABLE st_reservations (
	po_number varchar(50) NULL,
	agen_code varchar(20) NULL,
	supplier_code varchar(10) NULL,
	supplier_name varchar(50) NULL,
	station_name varchar(10) NULL,
	market varchar(30) NULL,
	advertiser varchar(50) NULL,
	product varchar(50) NULL,
	r_date timestamp(0) NULL,
	total_spots numeric NULL,
	total_gross numeric(15, 2) NULL,
	agency_discount numeric(13, 10) NULL,
	total_nett numeric(15, 2) NULL,
	local_tax numeric(5, 2) NULL,
	notes varchar(1000) NULL,
	po_type varchar(15) NULL,
	sales_approval bpchar(1) NULL,
	sales_adate timestamp(0) NULL,
	sales_auser varchar(10) NULL,
	traffic_action bpchar(1) NULL,
	traffic_adate timestamp(0) NULL,
	traffic_auser varchar(10) NULL,
	update_user varchar(10) NULL,
	update_date timestamp(0) NULL,
	row_id varchar(18) OPTIONS(key 'true') NOT NULL,
	prod_code varchar(20) NULL,
	client_code varchar(20) NULL,
	channel_code varchar(3) NULL,
	mo_no varchar(20) NULL,
	sales_code varchar(5) NULL,
	pack_type_gen varchar(10) NULL,
	confirm bpchar(1) NULL,
	booking_period_from timestamp(0) NULL,
	booking_period_to timestamp(0) NULL,
	curr_code varchar(5) NULL,
	"source" varchar(4) NULL,
	recvdt timestamp(0) NULL,
	ref_rid_sr varchar(18) NULL,
	ref_po_num varchar(50) NULL,
	pack_no varchar(30) NULL,
	posted varchar(1) NULL,
	po_user varchar(10) NULL,
	perf_inv_no varchar(30) NULL,
	ath_user varchar(10) NULL,
	ath_date timestamp(0) NULL,
	ath_remark varchar(100) NULL,
	level_open varchar(4) NULL,
	po_status bpchar(1) NULL,
	main_closed varchar(1) NULL,
	mm numeric(38) NULL,
	yy numeric(38) NULL,
	job_id varchar(100) NULL,
	isadditionalflag bpchar(1) NULL,
	agency_commission numeric(13, 10) NULL,
	rid_pkg_ext varchar(20) NULL,
	has_manual_invoice bpchar(1) NULL,
	job_no varchar(100) NULL,
	directclientpo bpchar(1) NULL,
	paymentmode bpchar(3) NULL,
	entryuser varchar(10) NULL,
	entrydate timestamp(0) NULL,
	entrydate_a timestamp(0) NULL,
	packageflag bpchar(1) NULL,
	free_spot numeric NULL,
	nonfree_spot numeric NULL,
	entryuser_a varchar(10) NULL,
	cprp_flag bpchar(1) NULL,
	comm_row_id varchar(18) NULL,
	comm_master numeric(13, 10) NULL,
	disc_row_id varchar(18) NULL,
	disc_master numeric(13, 10) NULL,
	po_change_status bpchar(1) NULL,
	sub_agen_code varchar(20) NULL,
	fix_bonus bpchar(1) NULL,
	bonus_prc numeric(5, 2) NULL,
	bonus_spot numeric NULL,
	bonus_budget numeric(15, 2) NULL,
	total_afterdisc numeric(15, 2) NULL,
	agency_disc1 numeric(13, 10) NULL,
	agency_disc2 numeric(13, 10) NULL,
	multidiscount_flag bpchar(1) NULL,
	inv_publisher varchar(5) NULL,
	baseon_dur_flag bpchar(1) NULL,
	free_duration int8 NULL,
	nonfree_duration int8 NULL,
	total_duration int8 NULL,
	tax_grp_code varchar(20) NULL,
	total_spot_ntc numeric NULL,
	po_receive varchar(20) NULL,
	bonus_duration int8 NULL,
	man_ros_prorate_flag varchar(1) NOT NULL,
	man_ros_prorate_user varchar(10) NULL,
	man_ros_prorate_date timestamp(0) NULL,
	man_ros_prorate_amt numeric(15, 2) NULL,
	man_ros_prorate_remarks varchar(100) NULL,
	man_bns_prorate_flag varchar(1) NOT NULL,
	man_bns_prorate_flag_user varchar(10) NULL,
	man_bns_prorate_flag_date timestamp(0) NULL,
	man_bns_prorate_flag_amt numeric(15, 2) NULL,
	man_bns_prorate_flag_remarks varchar(100) NULL,
	man_ntc_prorate_flag varchar(1) NOT NULL,
	man_ntc_prorate_user varchar(10) NULL,
	man_ntc_prorate_date timestamp(0) NULL,
	man_ntc_prorate_amt numeric(15, 2) NULL,
	man_ntc_prorate_remarks varchar(100) NULL,
	mkgd_apv1_flag varchar(1) NOT NULL,
	mkgd_apv1_user varchar(10) NULL,
	mkgd_apv1_date timestamp(0) NULL,
	mkgd_apv1_pct numeric(7, 2) NULL,
	mkgd_apv1_remarks varchar(100) NULL,
	mkgd_apv2_flag varchar(1) NOT NULL,
	mkgd_apv2_user varchar(10) NULL,
	mkgd_apv2_date timestamp(0) NULL,
	mkgd_apv2_pct numeric(7, 2) NULL,
	mkgd_apv2_remarks varchar(100) NULL,
	import_po varchar(1) NULL,
	amount_cost_budget numeric(15, 2) NULL,
	amount_actual_budget numeric(15, 2) NULL,
	keep_dummy bpchar(1) NULL,
	version_status bpchar(1) NULL,
	version_qty numeric NULL,
	max_per_hourprog numeric NULL,
	max_per_prog numeric NULL,
	max_per_break numeric NULL,
	casback_amount numeric(15, 2) NULL,
	casback_per numeric(5, 2) NULL,
	total_invoice numeric(15, 2) NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'ST_RESERVATIONS');