DROP MATERIALIZED VIEW IF EXISTS st_reservation_matrix1;

CREATE materialized VIEW st_reservation_matrix1 as
	SELECT 
		rid_stresmatrix,
		film_poc,
		row_id_poc,
		catslot_code,
		d1,
		d2,
		d3,
		d4,
		d5,
		d6,
		d7,
		d8,
		d9,
		d10,
		d11,
		d12,
		d13,
		d14,
		d15,
		d16,
		d17,
		d18,
		d19,
		d20,
		d21,
		d22,
		d23,
		d24,
		d25,
		d26,
		d27,
		d28,
		d29,
		d30,
		d31,
		row_id,
		update_user,
		update_date,
		line_num,
		spot_duration,
		spot_duration_sec,
		prod_code,
		prod_version,
		airtime_from,
		airtime_to,
		pref_cb,
		pref_spot,
		flag_rate,
		ed_rate_code,
		rate_price_trx,
		ath_user,
		ath_date,
		ath_remark,
		traffic_action,
		traffic_adate,
		traffic_auser,
		agency_rate,
		cancel_remark,
		row_id_cancel,
		schobj_code,
		line_remark,
		st_rate_amount,
		rid_pkg_int_lines,
		entry_user,
		st_rate_code,
		schobj_time,
		ridflagrate,
		schemecode,
		premiummethod,
		rid_seqprem,
		seqpremamt,
		prembasedon,
		rateafterpremium,
		bookingdatetime,
		ros_flag,
		rateprotectapply,
		entrydatetime,
		backupflag,
		agency_rate_changed,
		manual_rate,
		week_mon,
		week_tue,
		week_wed,
		week_thu,
		week_fri,
		week_sat,
		week_sun,
		agency_rate_po,
		spc_dt_start,
		spc_dt_end,
		fix_rate,
		manual_ros,
		manual_airtime_from,
		manual_airtime_to,
		rid_ros,
		agency_afterdisc,
		agency_nett,
		rid_cprp_int_lines,
		import_po,
		prem_pos_1,
		prem_pos_2,
		prem_pos_3,
		prem_pos_4,
		prem_pos_5,
		prem_pos_l1,
		prem_pos_l2,
		prem_pos_l3,
		prem_pos_l4,
		prem_pos_l5,
		prem_pos_lock
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					rid_stresmatrix,
					film_poc,
					row_id_poc,
					catslot_code,
					d1,
					d2,
					d3,
					d4,
					d5,
					d6,
					d7,
					d8,
					d9,
					d10,
					d11,
					d12,
					d13,
					d14,
					d15,
					d16,
					d17,
					d18,
					d19,
					d20,
					d21,
					d22,
					d23,
					d24,
					d25,
					d26,
					d27,
					d28,
					d29,
					d30,
					d31,
					row_id,
					update_user,
					update_date,
					line_num,
					spot_duration,
					spot_duration_sec,
					prod_code,
					prod_version,
					airtime_from,
					airtime_to,
					pref_cb,
					pref_spot,
					flag_rate,
					ed_rate_code,
					rate_price_trx,
					ath_user,
					ath_date,
					ath_remark,
					traffic_action,
					traffic_adate,
					traffic_auser,
					agency_rate,
					cancel_remark,
					row_id_cancel,
					schobj_code,
					line_remark,
					st_rate_amount,
					rid_pkg_int_lines,
					entry_user,
					st_rate_code,
					schobj_time,
					ridflagrate,
					schemecode,
					premiummethod,
					rid_seqprem,
					seqpremamt,
					prembasedon,
					rateafterpremium,
					bookingdatetime,
					ros_flag,
					rateprotectapply,
					entrydatetime,
					backupflag,
					agency_rate_changed,
					manual_rate,
					week_mon,
					week_tue,
					week_wed,
					week_thu,
					week_fri,
					week_sat,
					week_sun,
					agency_rate_po,
					spc_dt_start,
					spc_dt_end,
					fix_rate,
					manual_ros,
					manual_airtime_from,
					manual_airtime_to,
					rid_ros,
					agency_afterdisc,
					agency_nett,
					rid_cprp_int_lines,
					import_po,
					prem_pos_1,
					prem_pos_2,
					prem_pos_3,
					prem_pos_4,
					prem_pos_5,
					prem_pos_l1,
					prem_pos_l2,
					prem_pos_l3,
					prem_pos_l4,
					prem_pos_l5,
					prem_pos_lock
				FROM gen21.st_reservation_matrix1
			'
   		) tbl(
			rid_stresmatrix varchar(18),
			film_poc varchar(9),
			row_id_poc varchar(18),
			catslot_code varchar(3),
			d1 numeric,
			d2 numeric,
			d3 numeric,
			d4 numeric,
			d5 numeric,
			d6 numeric,
			d7 numeric,
			d8 numeric,
			d9 numeric,
			d10 numeric,
			d11 numeric,
			d12 numeric,
			d13 numeric,
			d14 numeric,
			d15 numeric,
			d16 numeric,
			d17 numeric,
			d18 numeric,
			d19 numeric,
			d20 numeric,
			d21 numeric,
			d22 numeric,
			d23 numeric,
			d24 numeric,
			d25 numeric,
			d26 numeric,
			d27 numeric,
			d28 numeric,
			d29 numeric,
			d30 numeric,
			d31 numeric,
			row_id varchar(18),
			update_user varchar(10),
			update_date timestamp(0),
			line_num int4,
			spot_duration varchar(8),
			spot_duration_sec int4,
			prod_code varchar(20),
			prod_version varchar(5),
			airtime_from varchar(8),
			airtime_to varchar(8),
			pref_cb numeric,
			pref_spot numeric,
			flag_rate varchar(20),
			ed_rate_code varchar(5),
			rate_price_trx numeric(25, 2),
			ath_user varchar(10),
			ath_date timestamp(0),
			ath_remark varchar(100),
			traffic_action bpchar(1),
			traffic_adate timestamp(0),
			traffic_auser varchar(10),
			agency_rate numeric(25, 2),
			cancel_remark varchar(40),
			row_id_cancel varchar(18),
			schobj_code varchar(5),
			line_remark varchar(100),
			st_rate_amount numeric(25, 5),
			rid_pkg_int_lines varchar(20),
			entry_user varchar(10),
			st_rate_code varchar(5),
			schobj_time bpchar(1),
			ridflagrate varchar(20),
			schemecode varchar(5),
			premiummethod bpchar(1),
			rid_seqprem varchar(20),
			seqpremamt numeric(25, 2),
			prembasedon bpchar(1),
			rateafterpremium numeric(25, 2),
			bookingdatetime timestamp(0),
			ros_flag bpchar(1),
			rateprotectapply bpchar(1),
			entrydatetime timestamp(0),
			backupflag bpchar(1),
			agency_rate_changed bpchar(1),
			manual_rate numeric(25, 2),
			week_mon bpchar(1),
			week_tue bpchar(1),
			week_wed bpchar(1),
			week_thu bpchar(1),
			week_fri bpchar(1),
			week_sat bpchar(1),
			week_sun bpchar(1),
			agency_rate_po numeric(25, 2),
			spc_dt_start timestamp(0),
			spc_dt_end timestamp(0),
			fix_rate bpchar(1),
			manual_ros bpchar(1),
			manual_airtime_from varchar(8),
			manual_airtime_to varchar(8),
			rid_ros varchar(20),
			agency_afterdisc numeric(15, 2),
			agency_nett numeric(15, 2),
			rid_cprp_int_lines varchar(20),
			import_po varchar(1),
			prem_pos_1 varchar(1),
			prem_pos_2 varchar(1),
			prem_pos_3 varchar(1),
			prem_pos_4 varchar(1),
			prem_pos_5 varchar(1),
			prem_pos_l1 varchar(1),
			prem_pos_l2 varchar(1),
			prem_pos_l3 varchar(1),
			prem_pos_l4 varchar(1),
			prem_pos_l5 varchar(1),
			prem_pos_lock varchar(1)
		)
with DATA
;
CREATE index idx_st_reservation_matrix1_row_id ON st_reservation_matrix1 (row_id);
