DROP FOREIGN TABLE IF EXISTS st_reservation_matrix1;

CREATE FOREIGN TABLE st_reservation_matrix1 (
	rid_stresmatrix varchar(18) NULL,
	film_poc varchar(9) NULL,
	row_id_poc varchar(18) NULL,
	catslot_code varchar(3) NULL,
	d1 numeric NULL,
	d2 numeric NULL,
	d3 numeric NULL,
	d4 numeric NULL,
	d5 numeric NULL,
	d6 numeric NULL,
	d7 numeric NULL,
	d8 numeric NULL,
	d9 numeric NULL,
	d10 numeric NULL,
	d11 numeric NULL,
	d12 numeric NULL,
	d13 numeric NULL,
	d14 numeric NULL,
	d15 numeric NULL,
	d16 numeric NULL,
	d17 numeric NULL,
	d18 numeric NULL,
	d19 numeric NULL,
	d20 numeric NULL,
	d21 numeric NULL,
	d22 numeric NULL,
	d23 numeric NULL,
	d24 numeric NULL,
	d25 numeric NULL,
	d26 numeric NULL,
	d27 numeric NULL,
	d28 numeric NULL,
	d29 numeric NULL,
	d30 numeric NULL,
	d31 numeric NULL,
	row_id varchar(18) OPTIONS(key 'true') NOT NULL,
	update_user varchar(10) NULL,
	update_date timestamp(0) NULL,
	line_num int4 NULL,
	spot_duration varchar(8) NULL,
	spot_duration_sec int4 NULL,
	prod_code varchar(20) NULL,
	prod_version varchar(5) NULL,
	airtime_from varchar(8) NULL,
	airtime_to varchar(8) NULL,
	pref_cb numeric NULL,
	pref_spot numeric NULL,
	flag_rate varchar(20) NULL,
	ed_rate_code varchar(5) NULL,
	rate_price_trx numeric(25, 2) NULL,
	ath_user varchar(10) NULL,
	ath_date timestamp(0) NULL,
	ath_remark varchar(100) NULL,
	traffic_action bpchar(1) NULL,
	traffic_adate timestamp(0) NULL,
	traffic_auser varchar(10) NULL,
	agency_rate numeric(25, 2) NULL,
	cancel_remark varchar(40) NULL,
	row_id_cancel varchar(18) NULL,
	schobj_code varchar(5) NULL,
	line_remark varchar(100) NULL,
	st_rate_amount numeric(25, 5) NULL,
	rid_pkg_int_lines varchar(20) NULL,
	entry_user varchar(10) NULL,
	st_rate_code varchar(5) NULL,
	schobj_time bpchar(1) NULL,
	ridflagrate varchar(20) NULL,
	schemecode varchar(5) NULL,
	premiummethod bpchar(1) NULL,
	rid_seqprem varchar(20) NULL,
	seqpremamt numeric(25, 2) NULL,
	prembasedon bpchar(1) NULL,
	rateafterpremium numeric(25, 2) NULL,
	bookingdatetime timestamp(0) NULL,
	ros_flag bpchar(1) NULL,
	rateprotectapply bpchar(1) NULL,
	entrydatetime timestamp(0) NULL,
	backupflag bpchar(1) NULL,
	agency_rate_changed bpchar(1) NULL,
	manual_rate numeric(25, 2) NULL,
	week_mon bpchar(1) NULL,
	week_tue bpchar(1) NULL,
	week_wed bpchar(1) NULL,
	week_thu bpchar(1) NULL,
	week_fri bpchar(1) NULL,
	week_sat bpchar(1) NULL,
	week_sun bpchar(1) NULL,
	agency_rate_po numeric(25, 2) NULL,
	spc_dt_start timestamp(0) NULL,
	spc_dt_end timestamp(0) NULL,
	fix_rate bpchar(1) NULL,
	manual_ros bpchar(1) NULL,
	manual_airtime_from varchar(8) NULL,
	manual_airtime_to varchar(8) NULL,
	rid_ros varchar(20) NULL,
	agency_afterdisc numeric(15, 2) NULL,
	agency_nett numeric(15, 2) NULL,
	rid_cprp_int_lines varchar(20) NULL,
	import_po varchar(1) NULL,
	prem_pos_1 varchar(1) NOT NULL,
	prem_pos_2 varchar(1) NOT NULL,
	prem_pos_3 varchar(1) NOT NULL,
	prem_pos_4 varchar(1) NOT NULL,
	prem_pos_5 varchar(1) NOT NULL,
	prem_pos_l1 varchar(1) NOT NULL,
	prem_pos_l2 varchar(1) NOT NULL,
	prem_pos_l3 varchar(1) NOT NULL,
	prem_pos_l4 varchar(1) NOT NULL,
	prem_pos_l5 varchar(1) NOT NULL,
	prem_pos_lock varchar(1) NOT NULL
)
SERVER gen21
OPTIONS (schema 'GEN21_TRANS7', table 'ST_RESERVATION_MATRIX1');