DROP MATERIALIZED VIEW IF EXISTS st_reservations cascade;

CREATE materialized VIEW st_reservations as
	SELECT 
		po_number,
		agen_code,
		supplier_code,
		supplier_name,
		station_name,
		market,
		advertiser,
		product,
		r_date,
		total_spots,
		total_gross,
		agency_discount,
		total_nett,
		local_tax,
		notes,
		po_type,
		sales_approval,
		sales_adate,
		sales_auser,
		traffic_action,
		traffic_adate,
		traffic_auser,
		update_user,
		update_date,
		row_id,
		prod_code,
		client_code,
		channel_code,
		mo_no,
		sales_code,
		pack_type_gen,
		confirm,
		booking_period_from,
		booking_period_to,
		curr_code,
		"source",
		recvdt,
		ref_rid_sr,
		ref_po_num,
		pack_no,
		posted,
		po_user,
		perf_inv_no,
		ath_user,
		ath_date,
		ath_remark,
		level_open,
		po_status,
		main_closed,
		mm,
		yy,
		job_id,
		isadditionalflag,
		agency_commission,
		rid_pkg_ext,
		has_manual_invoice,
		job_no,
		directclientpo,
		paymentmode,
		entryuser,
		entrydate,
		entrydate_a,
		packageflag,
		free_spot,
		nonfree_spot,
		entryuser_a,
		cprp_flag,
		comm_row_id,
		comm_master,
		disc_row_id,
		disc_master,
		po_change_status,
		sub_agen_code,
		fix_bonus,
		bonus_prc,
		bonus_spot,
		bonus_budget,
		total_afterdisc,
		agency_disc1,
		agency_disc2,
		multidiscount_flag,
		inv_publisher,
		baseon_dur_flag,
		free_duration,
		nonfree_duration,
		total_duration,
		tax_grp_code,
		total_spot_ntc,
		po_receive,
		bonus_duration,
		man_ros_prorate_flag,
		man_ros_prorate_user,
		man_ros_prorate_date,
		man_ros_prorate_amt,
		man_ros_prorate_remarks,
		man_bns_prorate_flag,
		man_bns_prorate_flag_user,
		man_bns_prorate_flag_date,
		man_bns_prorate_flag_amt,
		man_bns_prorate_flag_remarks,
		man_ntc_prorate_flag,
		man_ntc_prorate_user,
		man_ntc_prorate_date,
		man_ntc_prorate_amt,
		man_ntc_prorate_remarks,
		mkgd_apv1_flag,
		mkgd_apv1_user,
		mkgd_apv1_date,
		mkgd_apv1_pct,
		mkgd_apv1_remarks,
		mkgd_apv2_flag,
		mkgd_apv2_user,
		mkgd_apv2_date,
		mkgd_apv2_pct,
		mkgd_apv2_remarks,
		import_po,
		amount_cost_budget,
		amount_actual_budget,
		keep_dummy,
		version_status,
		version_qty,
		max_per_hourprog,
		max_per_prog,
		max_per_break,
		casback_amount,
		casback_per,
		total_invoice
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					po_number,
					agen_code,
					supplier_code,
					supplier_name,
					station_name,
					market,
					advertiser,
					product,
					r_date,
					total_spots,
					total_gross,
					agency_discount,
					total_nett,
					local_tax,
					notes,
					po_type,
					sales_approval,
					sales_adate,
					sales_auser,
					traffic_action,
					traffic_adate,
					traffic_auser,
					update_user,
					update_date,
					row_id,
					prod_code,
					client_code,
					channel_code,
					mo_no,
					sales_code,
					pack_type_gen,
					confirm,
					booking_period_from,
					booking_period_to,
					curr_code,
					"source",
					recvdt,
					ref_rid_sr,
					ref_po_num,
					pack_no,
					posted,
					po_user,
					perf_inv_no,
					ath_user,
					ath_date,
					ath_remark,
					level_open,
					po_status,
					main_closed,
					mm,
					yy,
					job_id,
					isadditionalflag,
					agency_commission,
					rid_pkg_ext,
					has_manual_invoice,
					job_no,
					directclientpo,
					paymentmode,
					entryuser,
					entrydate,
					entrydate_a,
					packageflag,
					free_spot,
					nonfree_spot,
					entryuser_a,
					cprp_flag,
					comm_row_id,
					comm_master,
					disc_row_id,
					disc_master,
					po_change_status,
					sub_agen_code,
					fix_bonus,
					bonus_prc,
					bonus_spot,
					bonus_budget,
					total_afterdisc,
					agency_disc1,
					agency_disc2,
					multidiscount_flag,
					inv_publisher,
					baseon_dur_flag,
					free_duration,
					nonfree_duration,
					total_duration,
					tax_grp_code,
					total_spot_ntc,
					po_receive,
					bonus_duration,
					man_ros_prorate_flag,
					man_ros_prorate_user,
					man_ros_prorate_date,
					man_ros_prorate_amt,
					man_ros_prorate_remarks,
					man_bns_prorate_flag,
					man_bns_prorate_flag_user,
					man_bns_prorate_flag_date,
					man_bns_prorate_flag_amt,
					man_bns_prorate_flag_remarks,
					man_ntc_prorate_flag,
					man_ntc_prorate_user,
					man_ntc_prorate_date,
					man_ntc_prorate_amt,
					man_ntc_prorate_remarks,
					mkgd_apv1_flag,
					mkgd_apv1_user,
					mkgd_apv1_date,
					mkgd_apv1_pct,
					mkgd_apv1_remarks,
					mkgd_apv2_flag,
					mkgd_apv2_user,
					mkgd_apv2_date,
					mkgd_apv2_pct,
					mkgd_apv2_remarks,
					import_po,
					amount_cost_budget,
					amount_actual_budget,
					keep_dummy,
					version_status,
					version_qty,
					max_per_hourprog,
					max_per_prog,
					max_per_break,
					casback_amount,
					casback_per,
					total_invoice
				FROM gen21.st_reservations
			'
   		) tbl(
			po_number varchar(50),
			agen_code varchar(20),
			supplier_code varchar(10),
			supplier_name varchar(50),
			station_name varchar(10),
			market varchar(30),
			advertiser varchar(50),
			product varchar(50),
			r_date timestamp(0),
			total_spots numeric,
			total_gross numeric(15, 2),
			agency_discount numeric(13, 10),
			total_nett numeric(15, 2),
			local_tax numeric(5, 2),
			notes varchar(1000),
			po_type varchar(15),
			sales_approval bpchar(1),
			sales_adate timestamp(0),
			sales_auser varchar(10),
			traffic_action bpchar(1),
			traffic_adate timestamp(0),
			traffic_auser varchar(10),
			update_user varchar(10),
			update_date timestamp(0),
			row_id varchar(18),
			prod_code varchar(20),
			client_code varchar(20),
			channel_code varchar(3),
			mo_no varchar(20),
			sales_code varchar(5),
			pack_type_gen varchar(10),
			confirm bpchar(1),
			booking_period_from timestamp(0),
			booking_period_to timestamp(0),
			curr_code varchar(5),
			"source" varchar(4),
			recvdt timestamp(0),
			ref_rid_sr varchar(18),
			ref_po_num varchar(50),
			pack_no varchar(30),
			posted varchar(1),
			po_user varchar(10),
			perf_inv_no varchar(30),
			ath_user varchar(10),
			ath_date timestamp(0),
			ath_remark varchar(100),
			level_open varchar(4),
			po_status bpchar(1),
			main_closed varchar(1),
			mm numeric(38),
			yy numeric(38),
			job_id varchar(100),
			isadditionalflag bpchar(1),
			agency_commission numeric(13, 10),
			rid_pkg_ext varchar(20),
			has_manual_invoice bpchar(1),
			job_no varchar(100),
			directclientpo bpchar(1),
			paymentmode bpchar(3),
			entryuser varchar(10),
			entrydate timestamp(0),
			entrydate_a timestamp(0),
			packageflag bpchar(1),
			free_spot numeric,
			nonfree_spot numeric,
			entryuser_a varchar(10),
			cprp_flag bpchar(1),
			comm_row_id varchar(18),
			comm_master numeric(13, 10),
			disc_row_id varchar(18),
			disc_master numeric(13, 10),
			po_change_status bpchar(1),
			sub_agen_code varchar(20),
			fix_bonus bpchar(1),
			bonus_prc numeric(5, 2),
			bonus_spot numeric,
			bonus_budget numeric(15, 2),
			total_afterdisc numeric(15, 2),
			agency_disc1 numeric(13, 10),
			agency_disc2 numeric(13, 10),
			multidiscount_flag bpchar(1),
			inv_publisher varchar(5),
			baseon_dur_flag bpchar(1),
			free_duration int8,
			nonfree_duration int8,
			total_duration int8,
			tax_grp_code varchar(20),
			total_spot_ntc numeric,
			po_receive varchar(20),
			bonus_duration int8,
			man_ros_prorate_flag varchar(1),
			man_ros_prorate_user varchar(10),
			man_ros_prorate_date timestamp(0),
			man_ros_prorate_amt numeric(15, 2),
			man_ros_prorate_remarks varchar(100),
			man_bns_prorate_flag varchar(1),
			man_bns_prorate_flag_user varchar(10),
			man_bns_prorate_flag_date timestamp(0),
			man_bns_prorate_flag_amt numeric(15, 2),
			man_bns_prorate_flag_remarks varchar(100),
			man_ntc_prorate_flag varchar(1),
			man_ntc_prorate_user varchar(10),
			man_ntc_prorate_date timestamp(0),
			man_ntc_prorate_amt numeric(15, 2),
			man_ntc_prorate_remarks varchar(100),
			mkgd_apv1_flag varchar(1),
			mkgd_apv1_user varchar(10),
			mkgd_apv1_date timestamp(0),
			mkgd_apv1_pct numeric(7, 2),
			mkgd_apv1_remarks varchar(100),
			mkgd_apv2_flag varchar(1),
			mkgd_apv2_user varchar(10),
			mkgd_apv2_date timestamp(0),
			mkgd_apv2_pct numeric(7, 2),
			mkgd_apv2_remarks varchar(100),
			import_po varchar(1),
			amount_cost_budget numeric(15, 2),
			amount_actual_budget numeric(15, 2),
			keep_dummy bpchar(1),
			version_status bpchar(1),
			version_qty numeric,
			max_per_hourprog numeric,
			max_per_prog numeric,
			max_per_break numeric,
			casback_amount numeric(15, 2),
			casback_per numeric(5, 2),
			total_invoice numeric(15, 2)
		)
with DATA
;
CREATE index idx_st_reservations_row_id ON st_reservations (row_id);
CREATE index idx_st_reservations_rid_pkg_ext ON st_reservations (rid_pkg_ext);
