DROP MATERIALIZED VIEW IF EXISTS tt_mo2 cascade;

CREATE materialized VIEW tt_mo2 as
	SELECT 
		row_id_spot,
		tx_time,
		prod_code,
		prod_version,
		cb_seq,
		spot_seq,
		rate_code,
		rate_amount,
		billed,
		verified,
		billed_date,
		verified_date,
		billed_user,
		verified_user,
		mo_book_date,
		mo_book_time,
		syn_rate,
		syn_version,
		invoiced,
		ack_traffic,
		tx_time_fp,
		update_date,
		update_user,
		traffic_desc,
		tr_user,
		tr_date,
		ack_remark,
		mo_no,
		org_rate_code,
		org_rate_amount,
		org_prod_version,
		inv_cancel,
		row_id_slot,
		backup_no,
		row_id_backup,
		verify_remarks,
		flag_system,
		act_film_poc,
		act_row_id_poc,
		act_cb_group_no,
		migration_data
   	FROM 
   		dblink(
   			'dbname=integration port=5432 host=172.16.123.121 user=postgres password=initrans7 ', 
   			'
				SELECT 
					row_id_spot,
					tx_time,
					prod_code,
					prod_version,
					cb_seq,
					spot_seq,
					rate_code,
					rate_amount,
					billed,
					verified,
					billed_date,
					verified_date,
					billed_user,
					verified_user,
					mo_book_date,
					mo_book_time,
					syn_rate,
					syn_version,
					invoiced,
					ack_traffic,
					tx_time_fp,
					update_date,
					update_user,
					traffic_desc,
					tr_user,
					tr_date,
					ack_remark,
					mo_no,
					org_rate_code,
					org_rate_amount,
					org_prod_version,
					inv_cancel,
					row_id_slot,
					backup_no,
					row_id_backup,
					verify_remarks,
					flag_system,
					act_film_poc,
					act_row_id_poc,
					act_cb_group_no,
					migration_data
				FROM gen21.tt_mo2
			'
   		) tbl(
			row_id_spot varchar(18),
			tx_time varchar(11),
			prod_code varchar(20),
			prod_version varchar(5),
			cb_seq numeric,
			spot_seq numeric,
			rate_code varchar(5),
			rate_amount numeric(15, 2),
			billed bpchar(1),
			verified bpchar(1),
			billed_date timestamp(0),
			verified_date timestamp(0),
			billed_user varchar(20),
			verified_user varchar(20),
			mo_book_date timestamp(0),
			mo_book_time varchar(8),
			syn_rate bpchar(1),
			syn_version bpchar(1),
			invoiced bpchar(1),
			ack_traffic bpchar(1),
			tx_time_fp varchar(8),
			update_date timestamp(0),
			update_user varchar(10),
			traffic_desc varchar(250),
			tr_user varchar(10),
			tr_date timestamp(0),
			ack_remark varchar(500),
			mo_no varchar(20),
			org_rate_code varchar(5),
			org_rate_amount numeric(15, 2),
			org_prod_version varchar(5),
			inv_cancel varchar(1),
			row_id_slot varchar(18),
			backup_no numeric,
			row_id_backup varchar(20),
			verify_remarks varchar(300),
			flag_system varchar(1),
			act_film_poc varchar(9),
			act_row_id_poc varchar(18),
			act_cb_group_no numeric,
			migration_data varchar(1)
		)
with DATA
;
CREATE unique index idx_tt_mo2_unique ON tt_mo2 (mo_no, row_id_spot);
